import type { CountryPlugData } from '../types';

const data: CountryPlugData = {
  slug: 'bangladesh-electric-plug-types-do-you-need-an-adapter',
  name: 'Bangladesh',
  demonym: 'Bangladeshi',
  continent: 'Asia',
  region: 'South Asia',
  voltage: 220,
  frequency: 50,
  complexityTier: 'moderate',
  plugTypes: [
    {
      id: 'type-c',
      name: 'Type C',
      subtitle: 'Europlug',
      pins: 2,
      pinShape: 'round',
      pinDiameter: 4.0,
      pinSpacing: 19,
      ratedAmps: 2.5,
      grounded: false,
      hasGroundClips: false,
      pinRadius: 0.063,
      bodyWidth: 1.18,
      bodyHeight: 0.72,
      bodyCornerRadius: 0.2,
      noseRadius: 0.42,
      recessRadius: 0.92,
      faceplateSize: 2.7,
    },
    {
      id: 'type-d',
      name: 'Type D',
      subtitle: 'Old British (India)',
      pins: 3,
      pinShape: 'round',
      pinDiameter: 5.08,
      pinSpacing: 19.1,
      ratedAmps: 5,
      grounded: true,
      hasGroundClips: false,
      pinRadius: 0.08,
      bodyWidth: 1.3,
      bodyHeight: 1.0,
      bodyCornerRadius: 0.2,
      noseRadius: 0.48,
      recessRadius: 1.0,
      faceplateSize: 2.8,
    },
    {
      id: 'type-g',
      name: 'Type G',
      subtitle: 'British',
      pins: 3,
      pinShape: 'rectangular',
      pinDiameter: 6.35,
      pinSpacing: 22.2,
      ratedAmps: 13,
      grounded: true,
      hasGroundClips: false,
      pinRadius: 0.08,
      bodyWidth: 1.6,
      bodyHeight: 1.2,
      bodyCornerRadius: 0.2,
      noseRadius: 0.55,
      recessRadius: 1.15,
      faceplateSize: 3.1,
    },
    {
      id: 'type-k',
      name: 'Type K',
      subtitle: 'Danish',
      pins: 3,
      pinShape: 'round',
      pinDiameter: 4.8,
      pinSpacing: 19,
      ratedAmps: 16,
      grounded: true,
      hasGroundClips: false,
      pinRadius: 0.075,
      bodyWidth: 1.3,
      bodyHeight: 1.3,
      bodyCornerRadius: 0.25,
      noseRadius: 0.52,
      recessRadius: 1.05,
      faceplateSize: 2.9,
    },
  ],
  quirks: [
    'Multiple plug types in use — a legacy of British rule (Type G/D) mixed with European influence (Type C) and some Danish-style (Type K). A universal adapter is strongly recommended.',
    'Power cuts are common, especially during the hot summer monsoon season. Most hotels in Dhaka have backup generators.',
  ],
  travelContext:
    'Bangladesh is not a country where you can predict which outlet you will encounter. The mix of four plug types means even moving between rooms in the same hotel can present different sockets. A universal adapter eliminates the guesswork. Power reliability has improved in Dhaka but remains patchy in rural and coastal areas.',
  adapterNeeded: [
    {
      origin: 'US / Canada',
      originPlugTypes: 'A, B',
      adapterNeeded: true,
      converterNeeded: 'maybe',
      notes:
        'US flat-pin plugs do not fit any Bangladeshi outlet type. You need a universal adapter. Bangladesh uses 220V — verify your devices are dual-voltage.',
    },
    {
      origin: 'UK',
      originPlugTypes: 'G',
      adapterNeeded: true,
      converterNeeded: false,
      notes:
        'Type G outlets exist in Bangladesh but are not universal. You may find them in some locations but encounter Type D or C in others. A universal adapter is the safest choice. Voltage is compatible.',
    },
    {
      origin: 'Europe (Schuko)',
      originPlugTypes: 'C, E, F',
      adapterNeeded: false,
      converterNeeded: false,
      notes:
        'Type C Europlugs fit many Bangladeshi outlets. You may occasionally encounter outlets that require a different plug, but Type C coverage is fairly good. Voltage is compatible.',
    },
    {
      origin: 'Australia / NZ',
      originPlugTypes: 'I',
      adapterNeeded: true,
      converterNeeded: false,
      notes:
        'Australian plugs do not match any Bangladeshi outlet type. Bring a universal adapter.',
    },
  ],
  localPurchaseOptions: [
    {
      name: 'Transcom Digital',
      type: 'electronics',
      city: 'Dhaka',
      priceRange: 'BDT 200–BDT 1,000',
      note: 'Electronics retailer with locations in major Dhaka shopping areas.',
    },
    {
      name: 'Walton Plaza',
      type: 'electronics',
      city: 'Dhaka',
      priceRange: 'BDT 200–BDT 800',
      note: 'Bangladeshi electronics brand with showrooms in major cities.',
    },
    {
      name: 'Bashundhara City shops',
      type: 'electronics',
      city: 'Dhaka',
      priceRange: 'BDT 150–BDT 600',
      note: 'Dhaka\'s largest shopping mall has many small electronics vendors selling adapters.',
    },
    {
      name: 'Hazrat Shahjalal Airport shops',
      type: 'airport',
      city: 'Dhaka',
      priceRange: 'BDT 400–BDT 1,500',
      note: 'Small shops in the arrivals area carry basic travel adapters.',
    },
  ],
  airportName: 'Hazrat Shahjalal International Airport',
  airportCode: 'DAC',
  neighbors: [
    {
      name: 'India',
      slug: 'india-electric-plug-types-will-you-need-an-adapter-traveling-to-india',
      plugTypes: ['C', 'D', 'M'],
      voltage: 230,
      sameAsSubject: 'mostly',
      adapterNote: 'India shares Types C and D with Bangladesh. Similar plug situation overall.',
    },
    {
      name: 'Myanmar',
      slug: 'myanmar-electric-plug-types-will-you-need-an-adapter-for-myanmar',
      plugTypes: ['C', 'D', 'F', 'G'],
      voltage: 230,
      sameAsSubject: 'partially',
      adapterNote: 'Myanmar shares Types C, D, and G with Bangladesh. A universal adapter covers both.',
    },
  ],
  hotelAdapterAvailability: 'sometimes',
  hotelUSBPorts: 'rare',
  hotelHairDryers: 'sometimes',
  accommodationNote:
    'International-standard hotels in Dhaka (Gulshan, Banani districts) are generally well-equipped with multiple outlet types and backup generators. Mid-range hotels may have a mix of outlet types. Budget guesthouses typically have basic outlets. Outside Dhaka, power reliability drops noticeably.',
  faqs: [
    {
      question: 'What adapter do I need for Bangladesh?',
      answer:
        'A universal adapter is the best choice because Bangladesh uses four different plug types (C, D, G, and K) with no consistent standard across locations. European travelers with Type C plugs may get by without one in many situations.',
    },
    {
      question: 'How reliable is the electricity in Bangladesh?',
      answer:
        'Dhaka and Chittagong have improved significantly in recent years, but power cuts still occur, particularly during peak summer demand and monsoon season. Most business-class hotels have generators. Carry a battery pack for peace of mind.',
    },
    {
      question: 'Is the voltage in Bangladesh safe for my devices?',
      answer:
        'Bangladesh uses 220V at 50Hz. Most phone chargers and laptop adapters are dual-voltage (100–240V) and will work fine. Single-voltage US appliances rated for 120V will need a converter or should be left at home.',
    },
    {
      question: 'Can I find adapters easily in Dhaka?',
      answer:
        'Yes. Electronics shops in Bashundhara City and the Gulshan area carry adapters at reasonable prices. Transcom Digital and Walton Plaza are reliable options. You can also find them at the airport on arrival.',
    },
  ],
  metaTitle: 'Bangladesh Power Plugs: Types C, D, G & K — Universal Adapter Recommended',
  metaDescription:
    'Bangladesh uses four plug types (C, D, G, K) at 220V/50Hz. Find out which adapter to bring, where to buy one in Dhaka, and what to expect from the power grid.',
  lastUpdated: '2025-06-01',
  relatedCountries: [
    { name: 'India', slug: 'india-electric-plug-types-will-you-need-an-adapter-traveling-to-india' },
    { name: 'Myanmar', slug: 'myanmar-electric-plug-types-will-you-need-an-adapter-for-myanmar' },
    { name: 'Nepal', slug: 'nepal-electric-plug-types-will-you-need-an-adapter-in-nepal' },
    { name: 'Sri Lanka', slug: 'sri-lanka-electric-plug-types-will-you-need-an-adapter-in-sri-lanka' },
  ],
};

export default data;
