import { CountryPlugData } from '../../types/country';

export const brazilData: CountryPlugData = {
  slug: 'brazil-electric-plug-types-do-you-need-an-adapter',
  name: 'Brazil',
  demonym: 'Brazilian',
  continent: 'South America',
  region: 'South America',
  voltage: 127,
  voltageNote: 'Voltage varies by state: São Paulo and Rio de Janeiro use 127V, while Brasília, Manaus, and most of the northeast use 220V. Always check locally — even neighboring cities can differ.',
  frequency: 60,
  complexityTier: 'complex',
  plugTypes: [
    { id: 'type-c', name: 'Type C', subtitle: 'Europlug', pins: 2, pinShape: 'round', pinDiameter: 4.0, pinSpacing: 19, ratedAmps: 2.5, grounded: false, hasGroundClips: false, pinRadius: 0.063, bodyWidth: 1.18, bodyHeight: 0.72, bodyCornerRadius: 0.2, noseRadius: 0.42, recessRadius: 0.92, faceplateSize: 2.7 },
    { id: 'type-n', name: 'Type N', subtitle: 'Brazilian', pins: 3, pinShape: 'round', pinDiameter: 4.0, pinSpacing: 19, ratedAmps: 20, grounded: true, hasGroundClips: false, pinRadius: 0.063, bodyWidth: 1.2, bodyHeight: 1.0, bodyCornerRadius: 0.2, noseRadius: 0.45, recessRadius: 0.95, faceplateSize: 2.7 },
  ],
  quirks: [
    'Brazil adopted its own unique plug standard — Type N (NBR 14136) — in 2011, replacing a chaotic mix of Type A, B, and C sockets that had accumulated over decades. It was specifically engineered to be safer and more compact than the alternatives.',
    'Voltage varies by state and sometimes by city. São Paulo, Rio de Janeiro, and much of the south run at 127V. Brasília, Recife, Salvador, Manaus, and most of the north and northeast run at 220V. The city of Campinas (near São Paulo) uses 220V while São Paulo itself uses 127V — you absolutely must check before plugging in high-power devices.',
    'Type C (Europlug) plugs fit into Type N sockets because the pin diameter and spacing are compatible. However, the reverse is not true — the three-pin Type N plug will not fit a standard Type C socket.',
    'Despite the 2011 standard, you\'ll still encounter old Type A and Type B (American-style) outlets in some older buildings and budget accommodations. A universal adapter is the safest bet.',
    'Many Brazilian hotels in tourist areas provide voltage adapters or have outlets labeled with their voltage. Some luxury hotels wire rooms at both 127V and 220V, with different outlets for each — check the labels on the outlet or ask reception.',
  ],
  recentChanges: 'Brazil mandated the NBR 14136 (Type N) standard in 2011 and has been phasing out all other outlet types since. New construction exclusively uses Type N, but the transition is still ongoing in older buildings.',
  travelContext: 'Brazil is one of the trickiest countries in the world for power — you need to worry about both the plug shape and the voltage, which can change from one city to the next.',
  adapterNeeded: [
    { origin: 'United States & Canada', originPlugTypes: 'Type A / Type B', adapterNeeded: true, converterNeeded: 'maybe', notes: 'US plugs don\'t fit modern Brazilian Type N sockets. You need an adapter. Voltage is the bigger concern: in São Paulo and Rio (127V), your 120V devices work fine. In Brasília or Manaus (220V), only dual-voltage devices are safe. Always check the local voltage before plugging in.' },
    { origin: 'Europe (Type C/E/F countries)', originPlugTypes: 'Type C / Type E / Type F', adapterNeeded: true, converterNeeded: 'maybe', notes: 'Type C Europlugs fit into Brazilian Type N sockets directly. Larger Type E/F (Schuko) plugs may not fit the recessed Type N socket and might need an adapter. Voltage is the real issue: in 127V areas, your 230V-only devices will underperform. In 220V areas, they\'ll be fine.' },
    { origin: 'United Kingdom & Ireland', originPlugTypes: 'Type G', adapterNeeded: true, converterNeeded: 'maybe', notes: 'UK plugs absolutely won\'t fit. You need a Type G to Type N adapter. In 220V areas of Brazil, your UK devices work well. In 127V areas, check for dual-voltage labels — single-voltage 230V devices won\'t work properly.' },
    { origin: 'Australia & New Zealand', originPlugTypes: 'Type I', adapterNeeded: true, converterNeeded: 'maybe', notes: 'Type I plugs don\'t fit Brazilian sockets. Bring an adapter. Same voltage concern — 220V areas are fine for Australian devices, 127V areas are not unless the device is dual-voltage.' },
    { origin: 'Argentina', originPlugTypes: 'Type C / Type I', adapterNeeded: true, converterNeeded: 'maybe', notes: 'Argentine Type C plugs fit Brazilian outlets. Type I plugs need an adapter. Argentina uses 220V, so in Brazil\'s 127V regions, single-voltage Argentine devices will struggle.' },
    { origin: 'Asia (varies)', originPlugTypes: 'Various', adapterNeeded: true, converterNeeded: 'maybe', notes: 'Most Asian travelers need an adapter. Japanese visitors: your Type A plugs won\'t fit Type N, and voltage varies — bring a universal adapter. Chinese travelers need an adapter; check voltage by destination city.' },
  ],
  localPurchaseOptions: [
    { name: 'Casas Bahia', type: 'electronics', note: 'One of Brazil\'s biggest electronics retailers — cheap adapters and voltage converters' },
    { name: 'Magazine Luiza', type: 'electronics', note: 'Major Brazilian electronics chain with adapters and power accessories' },
    { name: 'Kalunga', type: 'electronics', note: 'Office and electronics supplies — stocks travel adapters' },
    { name: 'Lojas Americanas', type: 'convenience', note: 'Variety store found everywhere in Brazil — basic adapters in the electronics section' },
    { name: 'São Paulo Guarulhos Airport (GRU) shops', type: 'airport', city: 'São Paulo', priceRange: 'R$30–80' },
  ],
  airportName: 'São Paulo/Guarulhos International Airport',
  airportCode: 'GRU',
  neighbors: [
    { name: 'Argentina', slug: 'argentina-electric-plug-types-do-you-need-an-adapter', plugTypes: ['C', 'I'], voltage: 220, sameAsSubject: 'partially', adapterNote: 'Argentina uses Type C (compatible) and Type I (needs adapter). Argentina is 220V — same as some Brazilian states, different from others.' },
    { name: 'Uruguay', slug: 'uruguay-electric-plug-types-which-adapter-will-you-need-in-uruguay', plugTypes: ['C', 'F', 'L'], voltage: 220, sameAsSubject: 'partially', adapterNote: 'Uruguay uses a mix of plug types at 220V. Type C works in Brazil but others need adapters.' },
    { name: 'Paraguay', slug: 'paraguay-electric-plug-types-which-adapter-will-you-need', plugTypes: ['C'], voltage: 220, sameAsSubject: 'partially', adapterNote: 'Paraguay uses Type C at 220V. Type C fits Brazilian sockets, but voltage may differ depending on the Brazilian state.' },
    { name: 'Colombia', slug: 'colombia-electric-plug-types-do-you-need-an-adapter', plugTypes: ['A', 'B'], voltage: 110, sameAsSubject: 'different', adapterNote: 'Colombia uses US-style Type A/B at 110V — different plug type from Brazil\'s Type N.' },
    { name: 'Venezuela', slug: 'venezuela-electric-plug-types-will-you-need-an-adapter-for-venezuela', plugTypes: ['A', 'B'], voltage: 120, sameAsSubject: 'different', adapterNote: 'Venezuela uses US-style Type A/B at 120V — different from Brazil\'s Type N.' },
  ],
  hotelAdapterAvailability: 'sometimes',
  hotelUSBPorts: 'sometimes',
  hotelHairDryers: 'common',
  accommodationNote: 'Hotels in São Paulo, Rio, and tourist areas like Salvador and Florianópolis often provide hair dryers and can usually lend you a plug adapter at reception. Some higher-end hotels have outlets wired at both 127V and 220V in the same room — look for labels near each outlet. Budget hostels and Airbnbs in older buildings might still have legacy Type A/B outlets mixed with newer Type N. USB ports in bedside panels are becoming more common at chain hotels but aren\'t universal yet.',
  deviceOverrides: [
    { device: 'Hair dryer / curling iron', dualVoltage: 'Check carefully — many are NOT dual-voltage', adapterOnly: 'Dangerous in 220V areas if device is 120V-only; useless in 127V areas if device is 230V-only', note: 'Brazil\'s voltage split makes hair dryers risky. Ask your hotel which voltage your room uses before plugging in. Many Brazilian hotels provide hair dryers — use theirs.' },
    { device: 'Laptop / phone charger', dualVoltage: 'Almost all modern chargers are 100–240V', adapterOnly: 'Yes, adapter only — works safely at either voltage', note: 'Your phone and laptop charger are almost certainly fine at any Brazilian voltage. Just bring a Type N adapter.' },
    { device: 'Electric shaver', dualVoltage: 'Most are 100–240V', adapterOnly: 'Usually fine with just an adapter', note: 'Check your shaver\'s label. Most modern ones handle any voltage.' },
    { device: 'CPAP machine', dualVoltage: 'Most major brands (ResMed, Philips) are 100–240V', adapterOnly: 'Adapter only for most models', note: 'Verify your specific model\'s voltage range. In Brazil, you must also confirm the room voltage — a 120V-only CPAP on a 220V outlet could be damaged.' },
  ],
  faqs: [
    { question: 'What plug type does Brazil use?', answer: 'Brazil uses Type N (NBR 14136) as its official standard — a three-pin round plug unique to Brazil. Type C (Europlug) also works because its two pins are compatible with Type N sockets. Older buildings may still have legacy Type A or B outlets.' },
    { question: 'Why does voltage change between Brazilian cities?', answer: 'Brazil never unified its power grid to a single voltage. Different states adopted different standards as the grid developed. São Paulo, Rio de Janeiro, and much of the south use 127V, while Brasília, Manaus, Recife, Salvador, and the northeast use 220V. The government chose to standardize the plug type (Type N) rather than forcing a costly voltage unification.' },
    { question: 'How do I know what voltage my Brazilian hotel room is?', answer: 'Check the outlet or the wall near the outlet — most hotels label the voltage. You can also ask at reception. In São Paulo and Rio, assume 127V. In Brasília, Recife, or Salvador, assume 220V. When in doubt, use only dual-voltage devices until you confirm.' },
    { question: 'Do European plugs work in Brazil?', answer: 'Type C (Europlug) plugs fit directly into Brazilian Type N sockets — the pin size and spacing match. Larger Schuko (Type F) plugs may not fit the recessed socket design and might need a small adapter. Voltage depends entirely on which city you\'re in.' },
    { question: 'Can I use my American devices in Brazil?', answer: 'Not without an adapter — US Type A/B plugs don\'t fit Brazil\'s Type N sockets. In 127V cities like São Paulo and Rio, your 120V devices will work fine once adapted. In 220V cities, only dual-voltage devices are safe. Always check.' },
    { question: 'What happens if I plug a 120V device into a 220V outlet in Brazil?', answer: 'It could overheat, be damaged, or create a safety hazard. This is a real risk in Brazil because you might not realize a city uses 220V. Always check the voltage before plugging in single-voltage devices. Dual-voltage devices (labeled "100–240V") are safe at any Brazilian outlet.' },
    { question: 'Where can I buy a plug adapter in São Paulo?', answer: 'Casas Bahia, Magazine Luiza, and Kalunga all carry adapters for under R$30. Lojas Americanas stocks basic adapters too. At Guarulhos Airport (GRU), expect to pay R$30–80. Most pharmacies and convenience stores do not carry adapters.' },
    { question: 'Is it safe to use a power strip in Brazil?', answer: 'Yes, but check the voltage rating. Power strips sold in Brazil are rated for the local voltage. If you bring one from abroad, ensure it\'s rated for the voltage of the city you\'re in. A 120V power strip on a 220V circuit could be dangerous.' },
  ],
  metaTitle: 'Brazil Power Plugs & Outlets — Adapters, Voltage by City (2026)',
  metaDescription: 'Brazil uses Type N and Type C plugs, but voltage varies between 127V and 220V by state. Find out which adapter you need and how to check voltage before you plug in.',
  lastUpdated: '2026-03-30',
  relatedCountries: [
    { name: 'Argentina', slug: 'argentina-electric-plug-types-do-you-need-an-adapter' },
    { name: 'United States', slug: 'usa-electric-plug-types-will-you-need-an-adapter-traveling-to-the-us' },
    { name: 'Uruguay', slug: 'uruguay-electric-plug-types-which-adapter-will-you-need-in-uruguay' },
    { name: 'Colombia', slug: 'colombia-electric-plug-types-do-you-need-an-adapter' },
    { name: 'Portugal', slug: 'portugal-electric-plug-types-will-you-need-adapter-in-lisbon-porto' },
  ],
};
