import type { CountryPlugData } from '../types';

const data: CountryPlugData = {
  slug: 'india-electric-plug-types-will-you-need-an-adapter-traveling-to-india',
  name: 'India',
  demonym: 'Indian',
  continent: 'Asia',
  region: 'South Asia',
  voltage: 230,
  frequency: 50,
  complexityTier: 'complex',
  plugTypes: [
    {
      id: 'type-c',
      name: 'Type C',
      subtitle: 'Europlug',
      pins: 2,
      pinShape: 'round',
      pinDiameter: 4.0,
      pinSpacing: 19,
      ratedAmps: 2.5,
      grounded: false,
      hasGroundClips: false,
      pinRadius: 0.063,
      bodyWidth: 1.18,
      bodyHeight: 0.72,
      bodyCornerRadius: 0.2,
      noseRadius: 0.42,
      recessRadius: 0.92,
      faceplateSize: 2.7,
    },
    {
      id: 'type-d',
      name: 'Type D',
      subtitle: 'Old British (India)',
      pins: 3,
      pinShape: 'round',
      pinDiameter: 5.08,
      pinSpacing: 19.1,
      ratedAmps: 5,
      grounded: true,
      hasGroundClips: false,
      pinRadius: 0.08,
      bodyWidth: 1.3,
      bodyHeight: 1.0,
      bodyCornerRadius: 0.2,
      noseRadius: 0.48,
      recessRadius: 1.0,
      faceplateSize: 2.8,
    },
    {
      id: 'type-m',
      name: 'Type M',
      subtitle: 'South African (large)',
      pins: 3,
      pinShape: 'round',
      pinDiameter: 7.06,
      pinSpacing: 25.4,
      ratedAmps: 15,
      grounded: true,
      hasGroundClips: false,
      pinRadius: 0.11,
      bodyWidth: 1.5,
      bodyHeight: 1.3,
      bodyCornerRadius: 0.2,
      noseRadius: 0.55,
      recessRadius: 1.15,
      faceplateSize: 3.1,
    },
  ],
  quirks: [
    'India uses three different plug types simultaneously. Type D (old British 5A standard with three round pins) is by far the most common in homes and hotels. Type M (larger 15A version) is used for high-power appliances like air conditioners and geysers. European Type C plugs fit most Indian sockets.',
    'Many Indian wall sockets combine both Type D (small, 5A) and Type M (large, 15A) holes in a single faceplate, creating a distinctive six-hole pattern. This combo socket is uniquely Indian and found almost everywhere.',
    'Electrical infrastructure quality varies enormously — five-star hotels in Mumbai have stable, well-grounded power, while budget guesthouses in Rajasthan may have loose sockets, exposed wiring, and unreliable grounding.',
    'Power outages (locally called "load shedding") are a fact of life outside major metro areas. Even in cities like Delhi and Bangalore, brief cuts during peak demand are not unusual. A portable power bank is essential for travel beyond the metros.',
    'India\'s electrical system is a direct inheritance from the British colonial period, which is why it shares plug types with other former British colonies like Pakistan, Nepal, and Sri Lanka — but not with modern Britain, which moved to Type G.',
  ],
  travelContext: 'India welcomes over 10 million international tourists annually across an enormous and diverse country. The electrical situation mirrors India itself: varied, occasionally chaotic, but ultimately workable. Most international travelers will need an adapter — the Type D socket is India-specific and unlike anything used in the US, Europe, or East Asia. European Type C plugs are the happy exception, fitting many Indian sockets directly. Bring a universal adapter, a power strip, and a portable battery to cover all scenarios.',
  adapterNeeded: [
    {
      origin: 'US / Canada',
      originPlugTypes: 'A, B',
      adapterNeeded: true,
      converterNeeded: false,
      notes: 'US flat-pin plugs do not fit Indian round-pin sockets. You\'ll need an adapter to Type D or Type C. Voltage (230V) is double the US — make sure all your devices are dual-voltage (100–240V). Most phone chargers and laptops are fine.',
    },
    {
      origin: 'UK',
      originPlugTypes: 'G',
      adapterNeeded: true,
      converterNeeded: false,
      notes: 'Despite the British colonial heritage, modern British Type G plugs do not fit Indian Type D sockets. You\'ll need an adapter. Voltage (230V/50Hz) is identical to the UK, so no converter needed.',
    },
    {
      origin: 'Europe',
      originPlugTypes: 'C, E, F',
      adapterNeeded: false,
      converterNeeded: false,
      notes: 'European Type C (Europlug) fits most Indian sockets directly — the round pins are compatible with Type D outlets. Bulkier Schuko (Type F) plugs with side clips may not fit as easily. Voltage (230V/50Hz) matches European standards.',
    },
    {
      origin: 'Australia / New Zealand',
      originPlugTypes: 'I',
      adapterNeeded: true,
      converterNeeded: false,
      notes: 'Australian Type I plugs are incompatible with Indian sockets. You\'ll need an adapter. Voltage is compatible at 230V.',
    },
    {
      origin: 'South Asia (Nepal, Sri Lanka, Bangladesh)',
      originPlugTypes: 'C, D, G',
      adapterNeeded: false,
      converterNeeded: false,
      notes: 'Nepal and Sri Lanka share India\'s Type D sockets — your plugs will work directly. Bangladesh uses a mix of Types C, D, G, and K — Type C and D plugs will work in India without issues.',
    },
  ],
  localPurchaseOptions: [
    {
      name: 'Croma',
      type: 'electronics',
      city: 'Delhi, Mumbai, Bangalore, major cities',
      priceRange: '₹150–₹1,500',
      note: 'India\'s largest electronics retail chain (Tata-owned). Reliable selection of adapters and converters in major malls.',
    },
    {
      name: 'Reliance Digital',
      type: 'electronics',
      city: 'Major cities nationwide',
      priceRange: '₹100–₹1,200',
      note: 'Well-stocked electronics chain with travel adapter sections. Found in most shopping malls across India.',
    },
    {
      name: 'Vijay Sales',
      type: 'electronics',
      city: 'Mumbai, Delhi, NCR',
      priceRange: '₹100–₹1,000',
      note: 'Popular electronics retailer concentrated in western India. Good prices on adapters and power accessories.',
    },
    {
      name: 'Local electronics bazaars',
      type: 'electronics',
      city: 'Nationwide (Nehru Place in Delhi, Lamington Road in Mumbai)',
      priceRange: '₹30–₹500',
      note: 'India\'s legendary electronics markets sell adapters for a fraction of retail prices. Bargaining is expected. Quality varies — test before you buy.',
    },
    {
      name: 'Delhi Indira Gandhi / Mumbai Airport shops',
      type: 'airport',
      city: 'Delhi, Mumbai',
      priceRange: '₹300–₹2,000',
      note: 'Both major international airports have electronics shops in arrivals. Prices are marked up significantly over city rates but available 24/7.',
    },
    {
      name: 'Hotel front desk',
      type: 'hotel',
      note: 'Most mid-range and luxury Indian hotels keep adapters at the front desk. Ask on check-in. Some may charge a small deposit.',
    },
  ],
  airportName: 'Delhi Indira Gandhi International / Mumbai Chhatrapati Shivaji Maharaj International',
  airportCode: 'DEL / BOM',
  neighbors: [
    {
      name: 'Nepal',
      slug: 'nepal-electric-plug-types-will-you-need-an-adapter-in-nepal',
      plugTypes: ['C', 'D', 'M'],
      voltage: 230,
      sameAsSubject: 'identical',
      adapterNote: 'Nepal uses the same plug types and voltage as India. Your adapters will work in both countries without changes.',
    },
    {
      name: 'Bangladesh',
      slug: 'bangladesh-electric-plug-types-do-you-need-an-adapter',
      plugTypes: ['C', 'D', 'G', 'K'],
      voltage: 220,
      sameAsSubject: 'mostly',
      adapterNote: 'Bangladesh shares Types C and D with India, though some outlets are British Type G. Your India adapter will mostly work.',
    },
    {
      name: 'Sri Lanka',
      slug: 'sri-lanka-electric-plug-types-will-you-need-an-adapter-in-sri-lanka',
      plugTypes: ['D', 'G', 'M'],
      voltage: 230,
      sameAsSubject: 'mostly',
      adapterNote: 'Sri Lanka uses Types D and M like India, plus British Type G in some buildings. Your India adapter should work in most situations.',
    },
    {
      name: 'Pakistan',
      slug: 'pakistan-electric-plug-types-will-you-need-an-adapter',
      plugTypes: ['C', 'D', 'G', 'M'],
      voltage: 230,
      sameAsSubject: 'mostly',
      adapterNote: 'Pakistan shares Types C, D, and M with India. Some buildings also use British Type G. Very similar electrical setup overall.',
    },
    {
      name: 'Bhutan',
      slug: 'bhutan-electric-plug-types-do-you-need-an-adapter-in-bhutan',
      plugTypes: ['C', 'D', 'F', 'G'],
      voltage: 230,
      sameAsSubject: 'mostly',
      adapterNote: 'Bhutan shares Types C and D with India. Some buildings have Types F and G as well. India adapters generally work fine.',
    },
    {
      name: 'Myanmar',
      slug: 'myanmar-electric-plug-types-will-you-need-an-adapter-for-myanmar',
      plugTypes: ['C', 'D', 'F', 'G'],
      voltage: 230,
      sameAsSubject: 'partially',
      adapterNote: 'Myanmar has a mixed plug situation with Types C, D, F, and G. Your India adapter will cover Types C and D, but you may encounter Type G outlets.',
    },
  ],
  hotelAdapterAvailability: 'common',
  hotelUSBPorts: 'sometimes',
  hotelHairDryers: 'common',
  accommodationNote: 'India\'s hotel landscape spans from world-class luxury chains to basic roadside lodges, and the electrical experience varies accordingly. Five-star hotels in Delhi, Mumbai, and Bangalore typically have universal outlets, USB ports, and stable power with backup generators. Mid-range hotels usually have Type D sockets and can lend adapters. Budget guesthouses may have older wiring and loose sockets — inspect before use. Many hotels above three stars have backup generators for load shedding.',
  deviceOverrides: [
    {
      device: 'iPhone / smartphone charger',
      dualVoltage: 'Yes — all Apple and major brand chargers are rated 100–240V.',
      adapterOnly: 'European plugs fit directly. US/UK/AU travelers need a plug adapter.',
      note: 'A European-style Europlug (Type C) charger is the most convenient option for India, as it fits most outlets directly.',
    },
    {
      device: 'Laptop',
      dualVoltage: 'Yes — virtually all laptop power bricks accept 100–240V.',
      adapterOnly: 'European plugs fit directly. Others need an adapter.',
      note: 'Bring a surge protector if using expensive equipment — voltage fluctuations are common outside major cities.',
    },
    {
      device: 'Hair dryer / straightener',
      dualVoltage: 'Check carefully — many US models are 120V only.',
      adapterOnly: 'Not sufficient if the device is single-voltage 120V — it will burn out on 230V.',
      note: 'European 230V hair dryers work at Indian voltage. US 120V dryers will be destroyed. Most mid-range and up hotels provide hair dryers.',
    },
  ],
  faqs: [
    {
      question: 'What type of adapter do I need for India?',
      answer: 'If you\'re coming from the US, UK, or Australia, you need an adapter that converts to India\'s Type D socket (three round pins, 5mm diameter). A universal travel adapter is the best option since it covers all three Indian plug types. If you\'re from Europe, your Type C Europlug likely fits Indian outlets directly.',
    },
    {
      question: 'Will my European Europlug work in India?',
      answer: 'Yes, in most cases. The thin round pins of a Type C Europlug fit into the round holes of Indian Type D sockets. This is one of the few convenient plug compatibilities for India. Bulkier Schuko (Type F) plugs may not fit as cleanly.',
    },
    {
      question: 'What is the difference between Type D and Type M in India?',
      answer: 'Type D has three 5mm round pins at 5A capacity — it\'s the standard socket for lights, fans, phone chargers, and small devices. Type M has three larger 7mm pins at 15A — it\'s used for air conditioners, water heaters (geysers), and other heavy appliances. Many Indian wall plates combine both in a single faceplate.',
    },
    {
      question: 'Should I worry about power outages in India?',
      answer: 'In major cities like Delhi, Mumbai, and Bangalore, power is reasonably reliable, though brief cuts during peak demand happen. In smaller cities, hill stations, and rural areas, daily load shedding of 2–8 hours is common. Carry a portable power bank rated at 10,000mAh or more. Hotels with star ratings typically have backup generators.',
    },
    {
      question: 'Do I need a voltage converter for India?',
      answer: 'For modern electronics (phones, laptops, cameras, tablets), no — they\'re almost all dual-voltage (100–240V). You only need a converter for single-voltage devices like some US hair dryers (120V only) or older appliances. Check the label on your device\'s charger.',
    },
    {
      question: 'Are Indian outlets grounded?',
      answer: 'Type D and Type M outlets are designed to be grounded, but actual grounding depends on the building\'s wiring. In luxury hotels and modern apartments, grounding is usually functional. In older buildings and budget accommodations, the ground pin may be present but not actually connected. Using a surge protector adds an extra layer of safety.',
    },
    {
      question: 'Can I charge my devices at Indian airports?',
      answer: 'Yes. Delhi (DEL) and Mumbai (BOM) airports have charging stations throughout the terminals with Type D outlets, some USB ports, and occasionally universal outlets. Some lounges also provide adapters. Carry your own adapter to be safe.',
    },
    {
      question: 'Is a surge protector worth bringing to India?',
      answer: 'Yes, especially if you\'re traveling beyond the major metros. Voltage fluctuations and power surges during monsoon season are common in India. A compact surge-protecting power strip also gives you extra outlets from a single adapter — very useful when your hotel room has limited sockets.',
    },
  ],
  metaTitle: 'India Power Plugs: Types C, D & M — Which Adapter Do You Need?',
  metaDescription: 'India uses Type C, D, and M plugs at 230V/50Hz. European plugs fit directly. US/UK/AU travelers need adapters. Power outages common — bring a battery pack.',
  lastUpdated: '2025-06-01',
  relatedCountries: [
    { name: 'Nepal', slug: 'nepal-electric-plug-types-will-you-need-an-adapter-in-nepal' },
    { name: 'Sri Lanka', slug: 'sri-lanka-electric-plug-types-will-you-need-an-adapter-in-sri-lanka' },
    { name: 'Bangladesh', slug: 'bangladesh-electric-plug-types-do-you-need-an-adapter' },
    { name: 'Thailand', slug: 'thailand-electric-plug-type-will-you-need-an-adapter-for-thailand' },
  ],
};

export default data;
