import type { CountryPlugData } from '../types';

const jordan: CountryPlugData = {
  slug: 'jordan-electric-plug-types-will-you-need-adapter-traveling-to-jordan',
  name: 'Jordan',
  demonym: 'Jordanian',
  continent: 'Asia',
  region: 'Middle East',
  voltage: 230,
  frequency: 50,
  complexityTier: 'moderate',
  plugTypes: [
    {
      id: 'type-c',
      name: 'Type C',
      subtitle: 'Europlug',
      pins: 2,
      pinShape: 'round',
      pinDiameter: 4.0,
      pinSpacing: 19,
      ratedAmps: 2.5,
      grounded: false,
      hasGroundClips: false,
      pinRadius: 0.063,
      bodyWidth: 1.18,
      bodyHeight: 0.72,
      bodyCornerRadius: 0.2,
      noseRadius: 0.42,
      recessRadius: 0.92,
      faceplateSize: 2.7,
    },
    {
      id: 'type-d',
      name: 'Type D',
      subtitle: 'Old British (India)',
      pins: 3,
      pinShape: 'round',
      pinDiameter: 5.08,
      pinSpacing: 19.1,
      ratedAmps: 5,
      grounded: true,
      hasGroundClips: false,
      pinRadius: 0.08,
      bodyWidth: 1.3,
      bodyHeight: 1.0,
      bodyCornerRadius: 0.2,
      noseRadius: 0.48,
      recessRadius: 1.0,
      faceplateSize: 2.8,
    },
    {
      id: 'type-f',
      name: 'Type F',
      subtitle: 'Schuko',
      pins: 2,
      pinShape: 'round',
      pinDiameter: 4.8,
      pinSpacing: 19,
      ratedAmps: 16,
      grounded: true,
      hasGroundClips: true,
      pinRadius: 0.075,
      bodyWidth: 1.3,
      bodyHeight: 1.3,
      bodyCornerRadius: 0.25,
      noseRadius: 0.52,
      recessRadius: 1.05,
      faceplateSize: 2.9,
    },
    {
      id: 'type-g',
      name: 'Type G',
      subtitle: 'British',
      pins: 3,
      pinShape: 'rectangular',
      pinDiameter: 6.35,
      pinSpacing: 22.2,
      ratedAmps: 13,
      grounded: true,
      hasGroundClips: false,
      pinRadius: 0.08,
      bodyWidth: 1.6,
      bodyHeight: 1.2,
      bodyCornerRadius: 0.2,
      noseRadius: 0.55,
      recessRadius: 1.15,
      faceplateSize: 3.1,
    },
  ],
  quirks: [
    'Jordan has one of the most eclectic socket mixes in the Middle East — you may encounter Type C, D, F, and G in the same building. Tourist hotels typically standardize on Type C/F.',
    'Wadi Rum desert camps vary dramatically: luxury camps have solar arrays and 24-hour power, while basic Bedouin camps may have no electricity at all.',
  ],
  travelContext:
    'Jordan is a bucket-list destination — Petra, the Dead Sea, Wadi Rum, and Amman\'s food scene. The mixed plug situation means a universal adapter is the wisest investment. Tourist infrastructure is well-developed in Amman, Petra, Aqaba, and the Dead Sea area. Wadi Rum camps are the wildcard for power availability.',
  adapterNeeded: [
    {
      origin: 'US / Canada',
      originPlugTypes: 'A, B',
      adapterNeeded: true,
      converterNeeded: false,
      notes:
        'US plugs are incompatible with all Jordanian socket types. A universal adapter is the best choice given Jordan\'s mix of C, D, F, and G outlets.',
    },
    {
      origin: 'UK / Ireland',
      originPlugTypes: 'G',
      adapterNeeded: true,
      converterNeeded: false,
      notes:
        'While some Jordanian buildings have Type G outlets, it is not universal. Bring an adapter to cover C/F sockets as well. A universal adapter is safest.',
    },
    {
      origin: 'Europe (Continental)',
      originPlugTypes: 'C, E, F',
      adapterNeeded: false,
      converterNeeded: false,
      notes:
        'Type C and F are commonly found in Jordanian hotels and modern buildings. European travelers generally do not need an adapter, though you may occasionally encounter a Type G or D outlet.',
    },
    {
      origin: 'Australia / New Zealand',
      originPlugTypes: 'I',
      adapterNeeded: true,
      converterNeeded: false,
      notes:
        'Type I is not used in Jordan. Bring a universal adapter.',
    },
  ],
  localPurchaseOptions: [
    {
      name: 'SmartBuy',
      type: 'electronics',
      city: 'Amman',
      priceRange: '2–8 JOD',
      note: 'Electronics retailer in Amman malls with travel adapters.',
    },
    {
      name: 'City Mall electronics shops',
      type: 'electronics',
      city: 'Amman',
      priceRange: '2–7 JOD',
      note: 'Several electronics vendors inside Amman\'s City Mall.',
    },
    {
      name: 'Safeway',
      type: 'supermarket',
      city: 'Amman',
      priceRange: '2–6 JOD',
      note: 'Jordan\'s leading supermarket chain — check the household/electronics aisle.',
    },
    {
      name: 'Queen Alia Airport shops',
      type: 'airport',
      city: 'Amman',
      priceRange: '4–10 JOD',
      note: 'Electronics kiosks in the arrivals area at AMM.',
    },
  ],
  airportName: 'Amman Queen Alia International',
  airportCode: 'AMM',
  neighbors: [
    {
      name: 'Israel',
      slug: 'israel-electric-plug-type-will-you-need-an-adapter-for-israel',
      plugTypes: ['C', 'H'],
      voltage: 230,
      sameAsSubject: 'partially',
      adapterNote: 'Israel uses Type C (compatible with Jordan) and Type H (unique to Israel). Type C devices work in both countries.',
    },
    {
      name: 'Syria',
      slug: 'syria-electric-plug-types-which-adapter-will-you-need-in-syria',
      plugTypes: ['C', 'E', 'L'],
      voltage: 220,
      sameAsSubject: 'partially',
      adapterNote: 'Syria uses C/E/L. Type C overlaps with Jordan.',
    },
    {
      name: 'Iraq',
      slug: 'iraq-electric-plug-types-will-you-need-an-adapter-traveling-to-iraq',
      plugTypes: ['C', 'D', 'G'],
      voltage: 230,
      sameAsSubject: 'mostly',
      adapterNote: 'Iraq uses the same C/D/G mix. Your Jordanian adapter should work.',
    },
    {
      name: 'Saudi Arabia',
      slug: 'saudi-arabia-electric-plug-types-which-adapter-will-you-need',
      plugTypes: ['G'],
      voltage: 220,
      sameAsSubject: 'partially',
      adapterNote: 'Saudi Arabia uses only Type G at 60Hz. Your Jordanian Type G adapter works, but you will lose access to C/D/F outlets.',
    },
  ],
  hotelAdapterAvailability: 'common',
  hotelUSBPorts: 'sometimes',
  hotelHairDryers: 'common',
  accommodationNote:
    'Tourist hotels in Amman, Petra, Aqaba, and the Dead Sea generally have Type C/F outlets and are well-standardized. Many hotels catering to international guests keep adapters at reception. Wadi Rum camps range from luxury glamping with solar-powered outlets to basic Bedouin tents with no electricity — confirm in advance.',
  faqs: [
    {
      question: 'Will there be electricity in my Wadi Rum desert camp?',
      answer:
        'It depends entirely on the camp. Luxury glamping operations (like Memories Aicha or Sun City Camp) have solar panels providing power in each tent. Basic Bedouin camps may have no electricity at all. Always confirm with your camp before arrival and bring a portable battery regardless.',
    },
    {
      question: 'Why does Jordan have so many different plug types?',
      answer:
        'Jordan\'s plug diversity reflects its history. British influence introduced Type G and D, while trade relationships with Europe brought Type C and F. Newer construction tends to favor Type C/F, but the mix persists in older buildings.',
    },
    {
      question: 'What kind of adapter works best for Jordan?',
      answer:
        'A universal travel adapter is the best investment. It covers Type C, D, F, and G outlets, so you are prepared no matter what socket you find in your hotel or Airbnb.',
    },
    {
      question: 'Can I charge my phone at Petra?',
      answer:
        'There are no public outlets at the Petra archaeological site, and you will spend many hours walking. Charge fully at your hotel in Wadi Musa the night before and carry a portable battery. Some restaurants near the Petra visitor center have outlets.',
    },
    {
      question: 'Do Dead Sea resorts have reliable power?',
      answer:
        'Yes. Dead Sea resorts are well-equipped with modern electrical systems, typically using Type C/F outlets. Power is reliable and most resorts provide hair dryers and sometimes adapters at reception.',
    },
  ],
  metaTitle: 'Jordan Power Plugs: Types C, D, F & G — Will You Need an Adapter?',
  metaDescription:
    'Jordan uses a mix of Type C, D, F, and G plugs at 230V/50Hz. A universal adapter is your best bet. Tips for Petra, Wadi Rum camps, and where to buy in Amman.',
  lastUpdated: '2025-06-01',
  relatedCountries: [
    { name: 'Israel', slug: 'israel-electric-plug-type-will-you-need-an-adapter-for-israel' },
    { name: 'Egypt', slug: 'egypt-electric-plug-type-will-you-need-an-adapter-in-egypt' },
    { name: 'Saudi Arabia', slug: 'saudi-arabia-electric-plug-types-which-adapter-will-you-need' },
    { name: 'Lebanon', slug: 'lebanon-electric-plug-types-will-you-need-an-adapter-in-beirut' },
  ],
};

export default jordan;
