import type { CountryPlugData } from '../types';

const data: CountryPlugData = {
  slug: 'myanmar-electric-plug-types-will-you-need-an-adapter-for-myanmar',
  name: 'Myanmar',
  demonym: 'Burmese',
  continent: 'Asia',
  region: 'Southeast Asia',
  voltage: 230,
  frequency: 50,
  complexityTier: 'complex',
  plugTypes: [
    {
      id: 'type-c',
      name: 'Type C',
      subtitle: 'Europlug',
      pins: 2,
      pinShape: 'round',
      pinDiameter: 4.0,
      pinSpacing: 19,
      ratedAmps: 2.5,
      grounded: false,
      hasGroundClips: false,
      pinRadius: 0.063,
      bodyWidth: 1.18,
      bodyHeight: 0.72,
      bodyCornerRadius: 0.2,
      noseRadius: 0.42,
      recessRadius: 0.92,
      faceplateSize: 2.7,
    },
    {
      id: 'type-d',
      name: 'Type D',
      subtitle: 'Old British (India)',
      pins: 3,
      pinShape: 'round',
      pinDiameter: 5.08,
      pinSpacing: 19.1,
      ratedAmps: 5,
      grounded: true,
      hasGroundClips: false,
      pinRadius: 0.08,
      bodyWidth: 1.3,
      bodyHeight: 1.0,
      bodyCornerRadius: 0.2,
      noseRadius: 0.48,
      recessRadius: 1.0,
      faceplateSize: 2.8,
    },
    {
      id: 'type-f',
      name: 'Type F',
      subtitle: 'Schuko',
      pins: 2,
      pinShape: 'round',
      pinDiameter: 4.8,
      pinSpacing: 19,
      ratedAmps: 16,
      grounded: true,
      hasGroundClips: true,
      pinRadius: 0.075,
      bodyWidth: 1.3,
      bodyHeight: 1.3,
      bodyCornerRadius: 0.25,
      noseRadius: 0.52,
      recessRadius: 1.05,
      faceplateSize: 2.9,
    },
    {
      id: 'type-g',
      name: 'Type G',
      subtitle: 'British',
      pins: 3,
      pinShape: 'rectangular',
      pinDiameter: 6.35,
      pinSpacing: 22.2,
      ratedAmps: 13,
      grounded: true,
      hasGroundClips: false,
      pinRadius: 0.08,
      bodyWidth: 1.6,
      bodyHeight: 1.2,
      bodyCornerRadius: 0.2,
      noseRadius: 0.55,
      recessRadius: 1.15,
      faceplateSize: 3.1,
    },
  ],
  quirks: [
    'Myanmar has one of the most unpredictable plug situations in Asia — four different types (C, D, F, G) in active use with no single enforced standard. You might find British, Indian, or European outlets in the same building. A universal adapter is essential.',
    'Power outages are frequent, especially outside Yangon. Many hotels and guesthouses rely on generators as backup, which may only run during certain hours.',
  ],
  travelContext:
    'Myanmar is a challenging destination for electrical planning. The lack of a single standard means you genuinely cannot predict what outlet you will encounter. A quality universal adapter and a portable battery pack are non-negotiable gear. Outside Yangon and Mandalay, treat reliable electricity as a bonus rather than a given.',
  adapterNeeded: [
    {
      origin: 'US / Canada',
      originPlugTypes: 'A, B',
      adapterNeeded: true,
      converterNeeded: 'maybe',
      notes:
        'US flat-pin plugs do not fit any of Myanmar\'s four outlet types. A universal adapter is the only practical solution. Check voltage — Myanmar uses 230V.',
    },
    {
      origin: 'UK',
      originPlugTypes: 'G',
      adapterNeeded: true,
      converterNeeded: false,
      notes:
        'Some Myanmar outlets are Type G (British), but not all. You may find your UK plug works in some rooms but not others. Carry a universal adapter for reliability. Voltage is compatible.',
    },
    {
      origin: 'Europe (Schuko)',
      originPlugTypes: 'C, E, F',
      adapterNeeded: true,
      converterNeeded: false,
      notes:
        'Type C and F outlets exist in Myanmar, but you may also encounter Type D or G sockets. A universal adapter ensures you are covered for all four types.',
    },
    {
      origin: 'Australia / NZ',
      originPlugTypes: 'I',
      adapterNeeded: true,
      converterNeeded: false,
      notes:
        'Australian Type I plugs do not match any of Myanmar\'s outlet types. Bring a universal adapter.',
    },
  ],
  localPurchaseOptions: [
    {
      name: 'City Mart',
      type: 'supermarket',
      city: 'Yangon',
      priceRange: 'K 3,000–K 15,000',
      note: 'Myanmar\'s main supermarket chain. Electronics section carries basic adapters.',
    },
    {
      name: 'Bogyoke Market shops',
      type: 'electronics',
      city: 'Yangon',
      priceRange: 'K 2,000–K 10,000',
      note: 'Local electronics vendors in Bogyoke (Scott) Market sell adapters and power strips.',
    },
    {
      name: 'Hotel reception',
      type: 'hotel',
      priceRange: 'Free (loaner)',
      note: 'Tourist-class hotels in Yangon, Mandalay, and Bagan often lend adapters.',
    },
  ],
  airportName: 'Yangon International / Mandalay International',
  airportCode: 'RGN / MDL',
  neighbors: [
    {
      name: 'India',
      slug: 'india-electric-plug-types-will-you-need-an-adapter-traveling-to-india',
      plugTypes: ['C', 'D', 'M'],
      voltage: 230,
      sameAsSubject: 'partially',
      adapterNote: 'India shares Type C and D with Myanmar. Some adapters work in both countries.',
    },
    {
      name: 'China',
      slug: '3-electric-plug-types-in-china-will-you-need-an-adapter',
      plugTypes: ['A', 'C', 'I'],
      voltage: 220,
      sameAsSubject: 'partially',
      adapterNote: 'China shares Type C with Myanmar but also uses different types.',
    },
    {
      name: 'Thailand',
      slug: 'thailand-electric-plug-type-will-you-need-an-adapter-for-thailand',
      plugTypes: ['A', 'B', 'C', 'F'],
      voltage: 220,
      sameAsSubject: 'partially',
      adapterNote: 'Thailand shares Type C and F. A universal adapter covers both countries.',
    },
    {
      name: 'Laos',
      slug: 'laos-electric-plug-types-which-adapter-will-you-need-in-laos',
      plugTypes: ['A', 'B', 'C', 'E', 'F'],
      voltage: 230,
      sameAsSubject: 'partially',
      adapterNote: 'Laos has a different mix but shares some types with Myanmar.',
    },
    {
      name: 'Bangladesh',
      slug: 'bangladesh-electric-plug-types-do-you-need-an-adapter',
      plugTypes: ['C', 'D', 'G', 'K'],
      voltage: 220,
      sameAsSubject: 'partially',
      adapterNote: 'Bangladesh shares Types C, D, and G with Myanmar.',
    },
  ],
  hotelAdapterAvailability: 'sometimes',
  hotelUSBPorts: 'rare',
  hotelHairDryers: 'sometimes',
  accommodationNote:
    'Upscale hotels in Yangon and Mandalay generally have adapters available and may have multi-standard outlets. Mid-range hotels in Bagan and Inle Lake are hit or miss. Budget guesthouses may have just one or two outlets of unpredictable type. Always ask about outlet types at check-in.',
  faqs: [
    {
      question: 'What adapter do I need for Myanmar?',
      answer:
        'A universal adapter is the only safe choice. Myanmar uses four different plug types (C, D, F, and G) with no single standard. Carrying a type-specific adapter risks finding the wrong socket in your room.',
    },
    {
      question: 'How often do power outages happen in Myanmar?',
      answer:
        'In Yangon, power is reasonably reliable though brief outages still occur. Outside major cities — including popular destinations like Bagan, Inle Lake, and Ngapali Beach — outages are common. Most tourist-oriented hotels have generators, but they may not run 24 hours.',
    },
    {
      question: 'Should I bring a battery pack to Myanmar?',
      answer:
        'Absolutely. A good portable battery pack is essential, especially if you are traveling outside Yangon and Mandalay. Power availability at rural guesthouses and during boat trips can be very limited.',
    },
    {
      question: 'Is the voltage in Myanmar consistent?',
      answer:
        'The nominal voltage is 230V at 50Hz, but actual voltage can fluctuate, especially in areas served by older infrastructure or generators. A surge protector is worth carrying for sensitive electronics.',
    },
  ],
  metaTitle: 'Myanmar Power Plugs: Types C, D, F & G — Universal Adapter Essential',
  metaDescription:
    'Myanmar uses four plug types (C, D, F, G) at 230V/50Hz with no consistent standard. Find out why a universal adapter is a must and what to expect from the power grid.',
  lastUpdated: '2025-06-01',
  relatedCountries: [
    { name: 'India', slug: 'india-electric-plug-types-will-you-need-an-adapter-traveling-to-india' },
    { name: 'Thailand', slug: 'thailand-electric-plug-type-will-you-need-an-adapter-for-thailand' },
    { name: 'Cambodia', slug: 'cambodia-electric-plug-types-will-you-need-an-adapter' },
    { name: 'Bangladesh', slug: 'bangladesh-electric-plug-types-do-you-need-an-adapter' },
  ],
};

export default data;
