import type { CountryPlugData } from '../types';

const data: CountryPlugData = {
  slug: 'south-korea-electric-plug-types-will-you-need-an-adapter-in-seoul',
  name: 'South Korea',
  demonym: 'Korean',
  continent: 'Asia',
  region: 'East Asia',
  voltage: 220,
  frequency: 60,
  frequencyNote: 'South Korea is one of the few 220V countries that uses 60Hz. Most 220V+ countries use 50Hz. This rarely causes issues with modern electronics.',
  complexityTier: 'moderate',
  plugTypes: [
    {
      id: 'type-c',
      name: 'Type C',
      subtitle: 'Europlug',
      pins: 2,
      pinShape: 'round',
      pinDiameter: 4.0,
      pinSpacing: 19,
      ratedAmps: 2.5,
      grounded: false,
      hasGroundClips: false,
      pinRadius: 0.063,
      bodyWidth: 1.18,
      bodyHeight: 0.72,
      bodyCornerRadius: 0.2,
      noseRadius: 0.42,
      recessRadius: 0.92,
      faceplateSize: 2.7,
    },
    {
      id: 'type-f',
      name: 'Type F',
      subtitle: 'Schuko',
      pins: 2,
      pinShape: 'round',
      pinDiameter: 4.8,
      pinSpacing: 19,
      ratedAmps: 16,
      grounded: true,
      hasGroundClips: true,
      pinRadius: 0.075,
      bodyWidth: 1.3,
      bodyHeight: 1.3,
      bodyCornerRadius: 0.25,
      noseRadius: 0.52,
      recessRadius: 1.05,
      faceplateSize: 2.9,
    },
  ],
  quirks: [
    'South Korea runs at 220V/60Hz — an unusual combination. Most 220V countries use 50Hz (like Europe), and most 60Hz countries use 110–120V (like the US). The 60Hz rarely matters for modern electronics but may affect older clocks or motors.',
    'Until 2009, parts of South Korea still used 110V alongside 220V. The nationwide transition to 220V is complete, but you may encounter very old references or signage mentioning 110V in aging buildings.',
    'Korean outlets look like standard European Schuko (Type F) with the characteristic round recess and side grounding clips. European round-pin plugs fit perfectly.',
    'Many Korean hotels — especially those catering to international tourists — provide universal adapters at the front desk free of charge. Just ask at check-in.',
  ],
  travelContext: 'South Korea has become one of Asia\'s hottest travel destinations, propelled by K-pop culture, cutting-edge technology, and exceptional food. Seoul, Busan, and Jeju Island welcome millions of visitors annually. The electrical system is straightforward — European-style round-pin outlets throughout — but catches American, British, and Australian travelers off guard. An adapter is essential for non-European visitors. The good news: South Korea is a tech-forward country where adapters are cheap, abundant, and available everywhere from airport convenience stores to the ubiquitous Daiso.',
  adapterNeeded: [
    {
      origin: 'US / Canada',
      originPlugTypes: 'A, B',
      adapterNeeded: true,
      converterNeeded: false,
      notes: 'US flat-pin plugs do not fit Korean round-pin outlets. You\'ll need an adapter. The voltage (220V) is nearly double the US 120V — verify your devices are dual-voltage (100–240V). All modern phone chargers and laptop adapters are. Do not plug in single-voltage 120V devices.',
    },
    {
      origin: 'UK',
      originPlugTypes: 'G',
      adapterNeeded: true,
      converterNeeded: false,
      notes: 'British Type G plugs won\'t fit Korean outlets. You\'ll need an adapter from rectangular to round pins. Voltage is compatible (220V vs 230V). Many Korean hotels provide adapters at the front desk.',
    },
    {
      origin: 'Europe',
      originPlugTypes: 'C, E, F',
      adapterNeeded: false,
      converterNeeded: false,
      notes: 'European Type C and Type F plugs fit Korean outlets directly — the sockets are identical Schuko style. French Type E plugs also fit. Voltage (220V) is compatible with European devices. You don\'t need anything extra.',
    },
    {
      origin: 'Australia / New Zealand',
      originPlugTypes: 'I',
      adapterNeeded: true,
      converterNeeded: false,
      notes: 'Australian Type I plugs are incompatible with Korean outlets. You\'ll need an adapter. Voltage (220V vs 230V) is close enough for all practical purposes.',
    },
    {
      origin: 'Japan',
      originPlugTypes: 'A',
      adapterNeeded: true,
      converterNeeded: false,
      notes: 'Japanese flat-pin plugs don\'t fit Korean round-pin outlets. You need an adapter. The voltage difference (100V to 220V) is significant — all devices must be dual-voltage.',
    },
  ],
  localPurchaseOptions: [
    {
      name: 'Lotte Hi-Mart',
      type: 'electronics',
      city: 'Seoul, Busan, major cities',
      priceRange: '₩3,000–₩15,000',
      note: 'South Korea\'s largest electronics retailer with stores in most neighborhoods and shopping centers. Excellent adapter selection.',
    },
    {
      name: 'Electromart (Shinsegae)',
      type: 'electronics',
      city: 'Seoul, major cities',
      priceRange: '₩3,000–₩20,000',
      note: 'Premium electronics store inside Shinsegae department stores. Carries high-quality travel adapters and multi-port chargers.',
    },
    {
      name: 'Daiso Korea',
      type: 'convenience',
      city: 'Nationwide',
      priceRange: '₩1,000–₩5,000',
      note: 'Budget variety store found everywhere. Stocks basic plug adapters and USB chargers at bargain prices.',
    },
    {
      name: 'Coupang (online, same-day delivery)',
      type: 'electronics',
      city: 'Nationwide',
      priceRange: '₩2,000–₩15,000',
      note: 'Korea\'s dominant e-commerce platform offers same-day or next-day delivery on adapters. Order from your hotel on arrival.',
    },
    {
      name: 'Seoul Incheon Airport shops',
      type: 'airport',
      city: 'Incheon',
      priceRange: '₩5,000–₩25,000',
      note: 'Electronics shops and convenience stores throughout Incheon\'s terminals carry travel adapters. Prices are higher than city stores but immediately accessible.',
    },
    {
      name: 'Hotel front desk',
      type: 'hotel',
      note: 'Many Korean hotels, especially international chains and those in Myeongdong, Gangnam, and Hongdae, lend adapters free of charge at the front desk. Ask on check-in.',
    },
  ],
  airportName: 'Seoul Incheon International Airport',
  airportCode: 'ICN',
  neighbors: [
    {
      name: 'Japan',
      slug: 'japan-electric-plug-types-will-you-need-an-adapter-probably-yes',
      plugTypes: ['A', 'B'],
      voltage: 100,
      sameAsSubject: 'different',
      adapterNote: 'Japan uses flat-pin Type A/B at just 100V — completely different from Korea\'s round-pin 220V system. You\'ll need different adapters for each country.',
    },
    {
      name: 'China',
      slug: '3-electric-plug-types-in-china-will-you-need-an-adapter',
      plugTypes: ['A', 'C', 'I'],
      voltage: 220,
      sameAsSubject: 'partially',
      adapterNote: 'China shares Type C with Korea and uses similar voltage. China\'s universal combo outlets will likely accept your European-style adapter. Your Korea adapter may partially work in China.',
    },
    {
      name: 'North Korea',
      slug: 'north-korea-electric-plug-types-will-you-need-an-adapter-yup',
      plugTypes: ['C', 'F'],
      voltage: 220,
      sameAsSubject: 'identical',
      adapterNote: 'North Korea uses the same plug types and voltage as South Korea.',
    },
  ],
  hotelAdapterAvailability: 'common',
  hotelUSBPorts: 'common',
  hotelHairDryers: 'standard',
  accommodationNote: 'South Korean hotels are generally modern and well-equipped. International chain hotels and most mid-range Korean hotels provide universal adapters at the front desk — just ask. USB charging ports in rooms are increasingly standard, especially in Seoul and Busan. Hair dryers are provided in nearly all hotels. Budget guesthouses (minbak) and traditional hanok stays may have fewer outlets and no adapter service.',
  deviceOverrides: [
    {
      device: 'iPhone / smartphone charger',
      dualVoltage: 'Yes — all Apple and major brand chargers are rated 100–240V.',
      adapterOnly: 'European plugs fit directly. US/UK/AU/JP travelers need a plug adapter only.',
      note: 'Many Korean hotels have USB ports in the room. You may not even need your charger brick.',
    },
    {
      device: 'Laptop',
      dualVoltage: 'Yes — virtually all laptop power bricks accept 100–240V.',
      adapterOnly: 'European plugs fit directly. Others need an adapter.',
      note: 'South Korea has excellent Wi-Fi coverage, so you\'ll want your laptop powered up. Check that your adapter fits the recessed Korean sockets.',
    },
    {
      device: 'Hair dryer / straightener',
      dualVoltage: 'Check the label — many US models are 120V only.',
      adapterOnly: 'Not sufficient if the device is single-voltage 120V.',
      note: 'A 120V US hair dryer on 220V will burn out immediately. Korean hotels always provide hair dryers. European 220V hair dryers work perfectly.',
    },
  ],
  faqs: [
    {
      question: 'What adapter do I need for South Korea?',
      answer: 'South Korea uses European-style Type C and Type F (Schuko) outlets with two round pins. If you\'re from the US, UK, Australia, or Japan, you need a round-pin adapter. European travelers don\'t need any adapter — your plugs fit directly.',
    },
    {
      question: 'Can I get an adapter at my Korean hotel?',
      answer: 'Very likely, yes. Most Korean hotels catering to international guests — especially in Seoul\'s tourist districts like Myeongdong, Gangnam, and Hongdae — keep adapters at the front desk. Some are free to borrow, others require a small deposit. Ask when you check in.',
    },
    {
      question: 'Does South Korea still use 110V anywhere?',
      answer: 'No. South Korea completed its nationwide transition from 110V to 220V in 2009. All outlets now deliver 220V. You may see outdated references to 110V in very old guidebooks or signage, but this is no longer the case anywhere in the country.',
    },
    {
      question: 'Why does South Korea use 60Hz instead of 50Hz?',
      answer: 'South Korea adopted 60Hz from American electrical influence during and after the Korean War, when US military infrastructure shaped the country\'s early power grid. Even after switching from 110V to 220V, the 60Hz frequency was retained. It\'s an unusual 220V/60Hz combination shared with few other countries.',
    },
    {
      question: 'Will my European plug fit Korean outlets?',
      answer: 'Yes, perfectly. Korean outlets are standard Schuko (Type F) design — the same as Germany, France, Spain, and most of continental Europe. Both Type C Europlugs and Type F Schuko plugs fit without any adapter.',
    },
    {
      question: 'Where can I buy an adapter in Seoul?',
      answer: 'Adapters are easy to find across Seoul. Daiso stores (on most major streets) sell them for as little as ₩1,000. Lotte Hi-Mart has the best selection. Convenience stores like CU and GS25 in tourist areas sometimes carry them. Incheon Airport shops sell them on arrival.',
    },
  ],
  metaTitle: 'South Korea Power Plugs: Types C & F — Do You Need an Adapter in Seoul?',
  metaDescription: 'South Korea uses European-style Type C and F plugs at 220V/60Hz. EU plugs fit directly. US/UK/AU travelers need adapters. Many hotels lend adapters free.',
  lastUpdated: '2025-06-01',
  relatedCountries: [
    { name: 'Japan', slug: 'japan-electric-plug-types-will-you-need-an-adapter-probably-yes' },
    { name: 'China', slug: '3-electric-plug-types-in-china-will-you-need-an-adapter' },
    { name: 'Taiwan', slug: 'taiwan-electric-plug-types-which-adaptor-you-need-for-taiwan' },
    { name: 'Germany', slug: 'germany-electric-plug-types-will-you-need-an-adapter-in-germany' },
  ],
};

export default data;
