import type { CountryPlugData } from '../types';

const data: CountryPlugData = {
  slug: 'thailand-electric-plug-type-will-you-need-an-adapter-for-thailand',
  name: 'Thailand',
  demonym: 'Thai',
  continent: 'Asia',
  region: 'Southeast Asia',
  voltage: 230,
  frequency: 50,
  complexityTier: 'complex',
  plugTypes: [
    {
      id: 'type-a',
      name: 'Type A',
      subtitle: 'US ungrounded',
      pins: 2,
      pinShape: 'flat',
      pinDiameter: 6.35,
      pinSpacing: 12.7,
      ratedAmps: 15,
      grounded: false,
      hasGroundClips: false,
      pinRadius: 0.05,
      bodyWidth: 1.0,
      bodyHeight: 0.7,
      bodyCornerRadius: 0.15,
      noseRadius: 0.35,
      recessRadius: 0.85,
      faceplateSize: 2.5,
    },
    {
      id: 'type-b',
      name: 'Type B',
      subtitle: 'US grounded',
      pins: 3,
      pinShape: 'flat',
      pinDiameter: 6.35,
      pinSpacing: 12.7,
      ratedAmps: 15,
      grounded: true,
      hasGroundClips: false,
      pinRadius: 0.05,
      bodyWidth: 1.2,
      bodyHeight: 0.9,
      bodyCornerRadius: 0.15,
      noseRadius: 0.4,
      recessRadius: 0.95,
      faceplateSize: 2.7,
    },
    {
      id: 'type-c',
      name: 'Type C',
      subtitle: 'Europlug',
      pins: 2,
      pinShape: 'round',
      pinDiameter: 4.0,
      pinSpacing: 19,
      ratedAmps: 2.5,
      grounded: false,
      hasGroundClips: false,
      pinRadius: 0.063,
      bodyWidth: 1.18,
      bodyHeight: 0.72,
      bodyCornerRadius: 0.2,
      noseRadius: 0.42,
      recessRadius: 0.92,
      faceplateSize: 2.7,
    },
    {
      id: 'type-o',
      name: 'Type O',
      subtitle: 'Thai standard',
      pins: 3,
      pinShape: 'round',
      pinDiameter: 4.8,
      pinSpacing: 19,
      ratedAmps: 16,
      grounded: true,
      hasGroundClips: false,
      pinRadius: 0.075,
      bodyWidth: 1.3,
      bodyHeight: 1.3,
      bodyCornerRadius: 0.25,
      noseRadius: 0.52,
      recessRadius: 1.05,
      faceplateSize: 2.9,
    },
  ],
  quirks: [
    'Thailand has no single enforced plug standard — you\'ll encounter Type A, B, C, and O sockets, sometimes in the same room. The lack of standardization is one of the most chaotic plug situations in Asia.',
    'Many Thai sockets are "universal" multi-shape outlets designed to accept both flat US-style pins and round European pins in a single faceplate. These hybrid outlets are extremely common in hotels and newer buildings.',
    'Type O (TIS 166-2549) is the official Thai national standard — three round pins in a triangular pattern. Newer buildings and condos are increasingly wired with Type O, but adoption is gradual.',
    'Older buildings and budget accommodations often have US-style Type A or B outlets, a legacy of American electrical influence in the region during the mid-20th century.',
    '7-Eleven stores are on virtually every street corner in Thai cities and sell cheap travel adapters, multi-outlet strips, and USB chargers for under 200 baht.',
  ],
  travelContext: 'Thailand is Southeast Asia\'s most popular tourist destination, drawing over 28 million international visitors annually to Bangkok, Chiang Mai, Phuket, and the islands. The country\'s eclectic mix of plug types is confusing on paper but surprisingly forgiving in practice — the widespread use of universal outlets means most travelers can plug in without an adapter. That said, bringing a universal adapter is still smart insurance, especially for beach bungalows and older guesthouses where outlet types are unpredictable.',
  adapterNeeded: [
    {
      origin: 'US / Canada',
      originPlugTypes: 'A, B',
      adapterNeeded: false,
      converterNeeded: 'maybe',
      notes: 'US-style Type A plugs fit the majority of Thai outlets, including universal sockets and the many remaining Type A/B outlets. You likely won\'t need a plug adapter. However, Thailand runs at 230V — check that your devices are dual-voltage (100–240V) before plugging in. Most phone chargers and laptops are fine.',
    },
    {
      origin: 'UK',
      originPlugTypes: 'G',
      adapterNeeded: true,
      converterNeeded: false,
      notes: 'British Type G plugs won\'t fit Thai outlets. You\'ll need an adapter. The voltage (230V) is the same as the UK, so no converter is needed. Many hotel universal outlets may accept Type G but don\'t rely on it.',
    },
    {
      origin: 'Europe',
      originPlugTypes: 'C, E, F',
      adapterNeeded: false,
      converterNeeded: false,
      notes: 'European Type C (Europlug) fits most Thai outlets, including universal sockets and Type O outlets. The voltage and frequency (230V/50Hz) are identical to most of Europe. You\'re very likely fine without an adapter, though bulkier Schuko (Type F) plugs with side clips may not fit all sockets.',
    },
    {
      origin: 'Australia / New Zealand',
      originPlugTypes: 'I',
      adapterNeeded: true,
      converterNeeded: false,
      notes: 'Australian Type I plugs won\'t fit standard Thai outlets. You\'ll need an adapter, though some universal sockets may accept angled flat pins. Voltage is compatible (230V).',
    },
    {
      origin: 'Japan',
      originPlugTypes: 'A',
      adapterNeeded: false,
      converterNeeded: false,
      notes: 'Japanese Type A plugs fit most Thai outlets directly. The voltage jump from 100V to 230V is the concern — make sure all your devices are rated for 230V input before plugging them in.',
    },
  ],
  localPurchaseOptions: [
    {
      name: '7-Eleven',
      type: 'convenience',
      city: 'Nationwide',
      priceRange: '฿50–฿300',
      note: 'Ubiquitous across Thailand — Bangkok alone has thousands. Stocks basic adapters, USB chargers, and power strips. Open 24 hours.',
    },
    {
      name: 'Power Buy',
      type: 'electronics',
      city: 'Bangkok, Chiang Mai, major cities',
      priceRange: '฿100–฿800',
      note: 'Thailand\'s dedicated electronics retailer, usually found in shopping malls. Best selection of adapters and converters.',
    },
    {
      name: 'HomePro',
      type: 'supermarket',
      city: 'Major cities',
      priceRange: '฿80–฿500',
      note: 'Home improvement chain with a good electrical section. Carries adapters, power strips, and voltage converters.',
    },
    {
      name: 'Big C',
      type: 'supermarket',
      city: 'Nationwide',
      priceRange: '฿60–฿400',
      note: 'Hypermarket chain with an electronics section. Affordable adapters and basic electrical accessories.',
    },
    {
      name: 'Bangkok Suvarnabhumi Airport shops',
      type: 'airport',
      city: 'Bangkok',
      priceRange: '฿200–฿1,000',
      note: 'Electronics kiosks in the arrivals hall and departure area sell travel adapters. Prices are marked up but convenient.',
    },
  ],
  airportName: 'Bangkok Suvarnabhumi Airport',
  airportCode: 'BKK',
  neighbors: [
    {
      name: 'Myanmar',
      slug: 'myanmar-electric-plug-types-will-you-need-an-adapter-for-myanmar',
      plugTypes: ['C', 'D', 'F', 'G'],
      voltage: 230,
      sameAsSubject: 'partially',
      adapterNote: 'Myanmar uses a different mix of plug types including British Type G. Your Thai adapter setup may not work — bring a universal adapter if visiting both countries.',
    },
    {
      name: 'Laos',
      slug: 'laos-electric-plug-types-which-adapter-will-you-need-in-laos',
      plugTypes: ['A', 'B', 'C', 'E', 'F'],
      voltage: 230,
      sameAsSubject: 'mostly',
      adapterNote: 'Laos shares many plug types with Thailand (A, B, C) and uses the same voltage. Your adapters should work in both countries.',
    },
    {
      name: 'Cambodia',
      slug: 'cambodia-electric-plug-types-will-you-need-an-adapter',
      plugTypes: ['A', 'C', 'G'],
      voltage: 230,
      sameAsSubject: 'mostly',
      adapterNote: 'Cambodia uses Types A and C like Thailand, plus some British Type G. Similar universal outlet situation — most adapters work in both countries.',
    },
    {
      name: 'Malaysia',
      slug: 'malaysia-electric-plug-types-will-you-need-an-adapter-in-kuala-lumpur',
      plugTypes: ['G'],
      voltage: 230,
      sameAsSubject: 'different',
      adapterNote: 'Malaysia uses exclusively British Type G at 230V. You\'ll likely need a different adapter when crossing from Thailand to Malaysia.',
    },
  ],
  hotelAdapterAvailability: 'sometimes',
  hotelUSBPorts: 'sometimes',
  hotelHairDryers: 'common',
  accommodationNote: 'Thai hotels range wildly in electrical setup. Luxury and international chain hotels typically have universal outlets or adapters at the front desk. Mid-range hotels in tourist areas usually have the universal multi-shape sockets that accept most plug types. Budget guesthouses and island bungalows may have older or improvised wiring — inspect outlets before plugging in expensive devices. USB charging ports are increasingly common in newer Bangkok hotels.',
  deviceOverrides: [
    {
      device: 'iPhone / smartphone charger',
      dualVoltage: 'Yes — all Apple and major brand chargers are rated 100–240V.',
      adapterOnly: 'US and European plugs usually fit Thai universal outlets directly. UK/AU travelers need an adapter.',
      note: 'Most travelers won\'t need anything extra for phone charging in Thailand.',
    },
    {
      device: 'Laptop',
      dualVoltage: 'Yes — virtually all laptop power bricks accept 100–240V.',
      adapterOnly: 'US and European plugs typically fit. UK/AU plugs need an adapter.',
      note: 'Check your power brick label to confirm. The universal outlets in most Thai hotels make this easy.',
    },
    {
      device: 'Hair dryer / straightener',
      dualVoltage: 'Check carefully — many travel hair dryers are 120V only (US) or 220–240V only (EU).',
      adapterOnly: 'Not if the device is single-voltage. A 120V-only dryer on 230V will burn out.',
      note: 'US travelers: do NOT plug in a 120V hair dryer — the 230V Thai current will damage it immediately. Use the hotel\'s dryer or buy one locally.',
    },
  ],
  faqs: [
    {
      question: 'Do I need an adapter for Thailand?',
      answer: 'It depends on where you\'re from. US and European travelers usually don\'t need one — most Thai outlets accept both flat US-style and round European pins thanks to universal sockets. UK and Australian travelers will need an adapter since Type G and Type I plugs don\'t fit Thai outlets.',
    },
    {
      question: 'What do Thai outlets look like?',
      answer: 'Thai outlets come in several varieties. The most common in hotels and newer buildings is the "universal" multi-shape socket that has slots for flat pins, round pins, and sometimes Type G rectangular pins all in one faceplate. You\'ll also see standard US-style two-slot outlets and the newer Thai Type O (three round pins in a triangle).',
    },
    {
      question: 'Is Thai voltage safe for my US electronics?',
      answer: 'Thailand uses 230V, which is nearly double the US 120V. Most modern chargers and laptop power bricks are dual-voltage (100–240V) and will work fine. Single-voltage US appliances like some hair dryers and older electronics will be destroyed by 230V — check the label before plugging in.',
    },
    {
      question: 'Can I buy an adapter at 7-Eleven in Thailand?',
      answer: 'Yes. Thailand\'s omnipresent 7-Eleven stores stock basic travel adapters, USB chargers, and power strips. Expect to pay 50–300 baht. The selection varies by store, so if one doesn\'t have what you need, try the next one (which is probably 50 meters away).',
    },
    {
      question: 'What is a Type O plug?',
      answer: 'Type O (TIS 166-2549) is Thailand\'s official national plug standard. It has three round pins arranged in a triangular pattern, similar to the shape of a European Type F but with a third grounding pin. It\'s being phased in as the standard for new construction, but older plug types remain widespread.',
    },
    {
      question: 'Will my European Schuko plug fit Thai outlets?',
      answer: 'A standard Europlug (Type C, two thin round pins) will fit most Thai outlets including universal sockets. However, the bulkier Schuko plug (Type F) with side grounding clips may not fit all Thai sockets, especially older Type A/B outlets. Carry a slim Europlug adapter as backup.',
    },
    {
      question: 'Are power outages common in Thailand?',
      answer: 'In Bangkok and major tourist areas, power is generally reliable. On the islands and in rural areas, brief outages during storms are not unusual. A portable battery pack is a good idea for island hopping and travel to remote areas.',
    },
    {
      question: 'Do Thai hotels provide adapters?',
      answer: 'Upscale and international chain hotels typically have universal outlets or lend adapters at the front desk. Mid-range hotels in tourist areas usually have the universal multi-shape sockets. Budget guesthouses and beach bungalows are less predictable — bring your own adapter to be safe.',
    },
  ],
  metaTitle: 'Thailand Power Plugs: Types A, B, C & O — Do You Need an Adapter?',
  metaDescription: 'Thailand uses a mix of Type A, B, C, and O plugs at 230V/50Hz. Universal outlets are common. US and EU plugs often fit directly. UK/AU travelers need an adapter.',
  lastUpdated: '2025-06-01',
  relatedCountries: [
    { name: 'Cambodia', slug: 'cambodia-electric-plug-types-will-you-need-an-adapter' },
    { name: 'Laos', slug: 'laos-electric-plug-types-which-adapter-will-you-need-in-laos' },
    { name: 'Malaysia', slug: 'malaysia-electric-plug-types-will-you-need-an-adapter-in-kuala-lumpur' },
    { name: 'Vietnam', slug: 'vietnam-electric-plug-types-which-adapter-will-you-need-for-vietnam' },
  ],
};

export default data;
