import type { CountryPlugData } from '../types';

const data: CountryPlugData = {
  slug: 'united-arab-emirates-electric-plug-types-which-adapter-for-uae',
  name: 'United Arab Emirates',
  demonym: 'Emirati',
  continent: 'Asia',
  region: 'Middle East',
  voltage: 230,
  frequency: 50,
  complexityTier: 'moderate',
  plugTypes: [
    {
      id: 'type-g',
      name: 'Type G',
      subtitle: 'British',
      pins: 3,
      pinShape: 'rectangular',
      pinDiameter: 6.35,
      pinSpacing: 22.2,
      ratedAmps: 13,
      grounded: true,
      hasGroundClips: false,
      pinRadius: 0.08,
      bodyWidth: 1.6,
      bodyHeight: 1.2,
      bodyCornerRadius: 0.2,
      noseRadius: 0.55,
      recessRadius: 1.15,
      faceplateSize: 3.1,
    },
  ],
  quirks: [
    'The UAE uses British Type G plugs — a legacy of the British protectorate era that ended in 1971. The system is identical to the UK, Singapore, Hong Kong, and Malaysia.',
    'Dubai and Abu Dhabi\'s luxury hotels are among the most electrically accommodating in the world. Many five-star hotels have universal outlets, built-in USB-C ports, and even wireless charging pads in rooms.',
    'Some older buildings in the northern emirates (Sharjah, Ajman, Ras Al Khaimah) may have Type C or Type D sockets alongside the standard Type G, reflecting older mixed wiring.',
    'UAE malls and public spaces frequently have free charging stations with universal outlets and USB ports — especially in Dubai Mall, Mall of the Emirates, and Abu Dhabi\'s Yas Mall.',
  ],
  travelContext: 'The UAE is one of the world\'s top tourist and business travel destinations, with Dubai alone attracting over 16 million international visitors annually. The country is built for global visitors — hotels are world-class, infrastructure is immaculate, and finding an adapter is never more than a short walk away. The electrical system is uniformly British Type G, so travelers from the UK will feel right at home while everyone else needs an adapter. Given how tech-forward the UAE is, many hotels solve this problem for you with universal outlets.',
  adapterNeeded: [
    {
      origin: 'US / Canada',
      originPlugTypes: 'A, B',
      adapterNeeded: true,
      converterNeeded: false,
      notes: 'US flat-pin plugs don\'t fit the UAE\'s British-style outlets. You\'ll need an adapter. Voltage (230V) is nearly double the US — make sure devices are dual-voltage (100–240V). All modern chargers and laptops handle this fine.',
    },
    {
      origin: 'UK',
      originPlugTypes: 'G',
      adapterNeeded: false,
      converterNeeded: false,
      notes: 'UK Type G plugs fit UAE outlets perfectly — identical system, identical voltage and frequency. No adapter or converter needed.',
    },
    {
      origin: 'Europe',
      originPlugTypes: 'C, E, F',
      adapterNeeded: true,
      converterNeeded: false,
      notes: 'European round-pin plugs don\'t fit the UAE\'s rectangular-pin outlets. You\'ll need an adapter. Voltage (230V/50Hz) is identical to Europe — no converter needed.',
    },
    {
      origin: 'Australia / New Zealand',
      originPlugTypes: 'I',
      adapterNeeded: true,
      converterNeeded: false,
      notes: 'Australian Type I plugs are incompatible with UAE Type G outlets. You\'ll need an adapter. Voltage is identical at 230V.',
    },
    {
      origin: 'India / South Asia',
      originPlugTypes: 'C, D, M',
      adapterNeeded: true,
      converterNeeded: false,
      notes: 'Indian plugs don\'t fit UAE Type G outlets. You\'ll need an adapter. Given the massive Indian expat population in the UAE, adapters for Indian-to-UK conversion are widely sold locally.',
    },
  ],
  localPurchaseOptions: [
    {
      name: 'Sharaf DG',
      type: 'electronics',
      city: 'Dubai, Abu Dhabi, Sharjah',
      priceRange: 'AED 10–AED 80',
      note: 'The UAE\'s largest electronics retailer with stores in every major mall. Excellent selection of travel adapters and multi-port chargers.',
    },
    {
      name: 'Carrefour',
      type: 'supermarket',
      city: 'Nationwide',
      priceRange: 'AED 8–AED 50',
      note: 'French hypermarket chain with a large UAE presence. Electronics sections stock adapters and power accessories at reasonable prices.',
    },
    {
      name: 'Lulu Hypermarket',
      type: 'supermarket',
      city: 'Nationwide',
      priceRange: 'AED 5–AED 40',
      note: 'Popular UAE-based hypermarket chain. Carries affordable adapters in the electronics aisle. Particularly well-stocked for Indian plug conversions.',
    },
    {
      name: 'Dubai International Airport (DXB)',
      type: 'airport',
      city: 'Dubai',
      priceRange: 'AED 20–AED 120',
      note: 'Duty-free shops and electronics kiosks in all terminals sell travel adapters. Dubai Duty Free is one of the world\'s largest. Prices are higher than city stores.',
    },
    {
      name: 'Hotel front desk / concierge',
      type: 'hotel',
      note: 'Most UAE hotels above three stars provide universal adapters at the front desk. Luxury hotels in Dubai and Abu Dhabi often have universal outlets or USB-C ports built into rooms.',
    },
  ],
  airportName: 'Dubai International Airport / Abu Dhabi International Airport',
  airportCode: 'DXB / AUH',
  neighbors: [
    {
      name: 'Saudi Arabia',
      slug: 'saudi-arabia-electric-plug-types-which-adapter-will-you-need',
      plugTypes: ['A', 'B', 'G'],
      voltage: 220,
      sameAsSubject: 'partially',
      adapterNote: 'Saudi Arabia uses Type G alongside Types A and B. Your UAE Type G adapter will work in some Saudi outlets, but the mix of plug types means you may need additional adapters.',
    },
    {
      name: 'Oman',
      slug: 'oman-electric-plug-types-which-adapter-will-you-need',
      plugTypes: ['C', 'G'],
      voltage: 240,
      sameAsSubject: 'mostly',
      adapterNote: 'Oman shares Type G with the UAE at a similar voltage. Your UAE adapter will work for most Omani outlets.',
    },
  ],
  hotelAdapterAvailability: 'common',
  hotelUSBPorts: 'common',
  hotelHairDryers: 'standard',
  accommodationNote: 'UAE hotels — particularly in Dubai and Abu Dhabi — are among the most tech-forward in the world. Five-star properties routinely feature universal outlets, USB-A and USB-C ports, wireless charging pads, and tablet-controlled room systems. Mid-range hotels provide adapters at the front desk and increasingly install universal outlets. Budget hotels and serviced apartments in older buildings may have only standard Type G sockets. Hair dryers are provided at virtually every accommodation level.',
  deviceOverrides: [
    {
      device: 'iPhone / smartphone charger',
      dualVoltage: 'Yes — all Apple and major brand chargers are rated 100–240V.',
      adapterOnly: 'UK plugs fit directly. US/EU/AU travelers need a plug adapter only.',
      note: 'Many UAE hotels have USB or USB-C ports in the room. Dubai Mall and other major malls have free public charging stations.',
    },
    {
      device: 'Laptop',
      dualVoltage: 'Yes — virtually all laptop power bricks accept 100–240V.',
      adapterOnly: 'UK plugs fit directly. Others need an adapter.',
      note: 'The UAE has fast Wi-Fi everywhere. Your laptop adapter is the only thing between you and connectivity.',
    },
    {
      device: 'Hair dryer / straightener',
      dualVoltage: 'Check the label — US models are often 120V only.',
      adapterOnly: 'Not sufficient if the device is single-voltage 120V — it will burn out on 230V.',
      note: 'UAE hotels provide high-quality hair dryers. European 220–240V hair dryers work perfectly. Do not plug in 120V US devices.',
    },
  ],
  faqs: [
    {
      question: 'What adapter do I need for Dubai?',
      answer: 'Dubai uses British-style Type G outlets (three rectangular pins). UK travelers don\'t need an adapter. US, European, Australian, and Asian travelers all need a Type G adapter. These are easy to find at Sharaf DG, Carrefour, Dubai Airport, or your hotel front desk.',
    },
    {
      question: 'Do Dubai hotels provide adapters?',
      answer: 'Most Dubai hotels provide universal adapters at the front desk — just ask at check-in. Many luxury hotels have gone further, installing universal outlets or USB-C ports in every room. Budget hotels may not have adapters available, so bring your own to be safe.',
    },
    {
      question: 'Is the plug the same in Abu Dhabi and Dubai?',
      answer: 'Yes. All seven emirates of the UAE use the same British Type G plug at 230V/50Hz. Your adapter works everywhere — Dubai, Abu Dhabi, Sharjah, Ajman, and the rest.',
    },
    {
      question: 'Can I use my US hair dryer in the UAE?',
      answer: 'Only if it\'s dual-voltage (check the label for "100–240V" or a voltage switch). Most US hair dryers are 120V only, and plugging a 120V device into 230V will destroy it instantly. UAE hotels provide hair dryers in every room — use those instead.',
    },
    {
      question: 'Are there older outlets in the UAE that aren\'t Type G?',
      answer: 'In newer parts of Dubai and Abu Dhabi, outlets are uniformly Type G. Some older buildings in Sharjah, Ajman, and Ras Al Khaimah may have Type C (European) or Type D (old British/Indian) sockets alongside Type G. This is uncommon in hotels but possible in older apartments.',
    },
    {
      question: 'Can I charge devices at Dubai Airport?',
      answer: 'Yes. Dubai International Airport (DXB) has charging stations throughout all terminals with both Type G outlets and USB ports. The airport lounges also provide adapters. Abu Dhabi\'s airport has similar facilities.',
    },
  ],
  metaTitle: 'UAE Power Plugs: Type G (British) — Which Adapter for Dubai & Abu Dhabi?',
  metaDescription: 'The UAE uses British Type G plugs at 230V/50Hz. UK plugs fit directly. US/EU/AU travelers need adapters. Hotels often provide them. Covers Dubai, Abu Dhabi, and all emirates.',
  lastUpdated: '2025-06-01',
  relatedCountries: [
    { name: 'Saudi Arabia', slug: 'saudi-arabia-electric-plug-types-which-adapter-will-you-need' },
    { name: 'Oman', slug: 'oman-electric-plug-types-which-adapter-will-you-need' },
    { name: 'Singapore', slug: 'singapur-electric-plug-types-will-you-need-an-adapter-for-singapur' },
    { name: 'United Kingdom', slug: 'united-kingdom-electric-plug-types-which-adapter-do-you-need-in-uk' },
  ],
};

export default data;
