const fs = require('fs');

// Load current data
const countriesData = JSON.parse(fs.readFileSync('./src/data/countries-plugs.json', 'utf8'));

// WordPress slug mappings (from the sitemap you provided)
const wordpressSlugs = {
  'af': 'afghanistan-electric-plug-types',  // Not the longer one they have
  'al': 'albanian-plug-types',
  'dz': 'algeria-electrical-plug-type', 
  'ad': 'andorra-plug-types-electric-sockets-used-in-andorra-adapter',
  'ao': 'angola-electric-plug-types-adapter',
  'ag': 'antigua-and-barbuda-electric-plug-types-adapter',
  'ar': 'argentina-electric-plug-types-do-you-need-an-adapter',
  'am': 'armenia-electric-socket-types-do-you-need-to-pack-an-adapter',
  'au': 'australia-electric-plug-types-do-you-need-adapter',
  'at': 'austria-electric-power-plug-types-do-you-need-an-adapter',
  'az': 'azerbaijan-electric-socket-types-will-you-need-an-adapter',
  'bs': 'bahamas-electric-socket-types-will-you-need-an-adapter',
  'bh': 'bahrain-electric-plug-types-will-you-need-an-adapter',
  'bd': 'bangladesh-electric-plug-types-do-you-need-an-adapter',
  'bb': 'barbados-electric-plug-types-do-you-need-an-adapter',
  'by': 'belarus-electric-plug-types-will-you-need-an-adapter',
  'be': 'belgium-electric-plug-types-do-you-need-an-adapter',
  'bz': 'belize-electric-plug-types-do-you-need-an-adapter',
  'bj': 'benin-electric-plug-types-do-you-need-an-adapter',
  'bt': 'bhutan-electric-plug-types-do-you-need-an-adapter-in-bhutan',
  'bo': 'bolivia-electric-plug-types-do-you-need-an-adapter',
  'ba': 'bosnia-and-herzegovina-electric-plug-types-is-adapter-needed',
  'bw': 'botswana-electric-plug-types-do-you-need-an-adapter',
  'br': 'brazil-electric-plug-types-do-you-need-an-adapter',
  'bn': 'brunei-electric-plug-types-do-you-need-an-adapter',
  'bg': 'bulgaria-electric-plug-types-do-you-need-an-adapter',
  'bf': 'burkina-faso-electric-plug-type-will-you-need-an-adapter',
  'bi': 'burundi-electric-plug-types-do-you-need-an-adapter',
  'cv': 'cabo-verde-electric-plug-types-do-you-need-an-adapter',
  'kh': 'cambodia-electric-plug-types-will-you-need-an-adapter',
  'cm': 'cameroon-electric-plug-types-do-you-need-to-pack-an-adapter',
  'ca': 'canada-electric-plug-types-do-you-need-an-adapter',
  'cf': 'central-african-republic-electric-plug-types-need-an-adapter',
  'td': 'chad-electric-plug-types-do-you-need-to-pack-an-adapter',
  'cl': 'chile-electric-plug-types-do-you-need-an-adapter-while-traveling',
  'cn': '3-electric-plug-types-in-china-will-you-need-an-adapter',
  'co': 'colombia-electric-plug-types-do-you-need-an-adapter',
  'km': 'comoros-electric-plug-type-do-you-need-an-adapter',
  'cg': 'congo-electric-plug-type-do-you-need-an-adapter',
  'cr': 'costa-rica-electric-plug-types-do-you-need-an-adapter',
  'ci': 'cote-divoire-electric-plug-type-do-you-need-an-adapter',
  'hr': 'croatia-electric-plug-types-do-you-need-to-take-adapter-on-trip',
  'cu': 'cuba-electric-plug-type-do-you-need-an-adapter-for-trip',
  'cy': 'cyprus-electric-plug-types-will-you-need-an-adapter',
  'cz': 'czech-republic-electric-plug-type-will-you-need-an-adapter',
  'dk': 'denmark-electric-plug-type-will-you-need-an-adapter-2',
  'dj': 'djibouti-electric-plug-types-do-you-need-to-take-an-adapter',
  'dm': 'dominica-electric-plug-types-will-you-need-an-adapter-with-you',
  'do': 'dominican-republic-electric-plug-types-do-you-need-an-adapter',
  'tl': 'east-timor-electric-plug-types-do-you-need-an-adapter',
  'ec': 'ecuador-electric-plug-type-will-you-need-an-adapter',
  'eg': 'egypt-electric-plug-type-will-you-need-an-adapter-in-egypt',
  'sv': 'el-salvador-electric-plug-type-will-you-need-an-adapter',
  'gq': 'equatorial-guinea-electric-plug-types-will-you-need-to-take-an-adapter-with-you',
  'er': 'eritrea-electric-plug-types-will-you-need-an-adapter-in-eritrea',
  'ee': 'estonia-electric-plug-types-will-you-need-an-adapter-in-estonia',
  'sz': 'eswatini-electric-plug-types-will-you-need-an-adapter-in-mbabane',
  'et': 'ethiopia-electric-plug-types-will-you-need-an-adapter-in-addis-abeba',
  'fj': 'fiji-electric-plug-types-will-you-need-an-adapter-in-suva',
  'fi': 'finland-electric-plug-type-will-you-need-an-adapter-in-helsinki',
  'fr': 'france-electric-plug-type-will-you-need-an-adapter-in-paris',
  'ga': 'gabon-electric-plug-types-will-you-need-an-adapter-libreville',
  'gm': 'gambia-electric-plug-types-will-you-need-an-adapter-in-banjul',
  'ge': 'georgia-electric-plug-types-will-you-need-an-adapter-in-tbilisi',
  'de': 'germany-electric-plug-types-will-you-need-an-adapter-in-germany',
  'gh': 'ghana-electric-plug-types-will-you-need-an-adapter-in-accra',
  'gr': 'greece-electric-plug-types-will-you-need-an-adapter-in-greece',
  'gd': 'grenada-electric-plug-types-will-you-need-an-adapter-in-grenada',
  'gt': 'guatemala-electric-plug-types-will-you-need-an-adapter-in-guatemala-city',
  'gn': 'guinea-electric-plug-types-will-you-need-an-adapter-in-conakry',
  'gw': 'guinea-bissau-electric-plug-type-will-you-need-an-adapter-in-bissau',
  'gy': 'guyana-electric-plug-types-will-you-need-an-adapter-in-georgetown',
  'ht': 'haiti-electric-plug-types-do-you-need-an-adapter-for-haiti',
  'hn': 'honduras-electric-plug-types-do-you-need-an-adapter-in-honduras',
  'hu': 'hungary-electric-plug-types-will-you-need-an-adapter-in-budapest',
  'is': 'iceland-electric-plug-types-will-you-need-an-adapter-in-reykjavik',
  'in': 'india-electric-plug-types-will-you-need-an-adapter-traveling-to-india',
  'id': 'indonesia-electric-plug-types-will-you-need-an-adapter-in-indonesia',
  'ir': 'iran-electric-plug-types-will-you-need-an-adapter-traveling-to-iran',
  'iq': 'iraq-electric-plug-types-will-you-need-an-adapter-traveling-to-iraq',
  'ie': 'ireland-electric-plug-types-will-you-need-an-adapter-for-ireland',
  'il': 'israel-electric-plug-type-will-you-need-an-adapter-for-israel',
  'it': 'italy-electric-plug-types-which-outlets-they-use-in-italy-adapters',
  'jm': 'jamaica-electric-plug-types-will-you-need-an-adapter-for-charging',
  'jp': 'japan-electric-plug-types-will-you-need-an-adapter-probably-yes',
  'jo': 'jordan-electric-plug-types-will-you-need-adapter-traveling-to-jordan',
  'kz': 'kazakhstan-electric-plug-types-will-you-need-an-adapter-probably-yes',
  'ke': 'kenya-electric-plug-types-will-you-need-an-adapter-traveling-to-kenya',
  'ki': 'kiribati-electric-plug-types-will-you-need-an-adapter-for-kiribati',
  'kp': 'north-korea-electric-plug-types-will-you-need-an-adapter-yup',
  'kr': 'south-korea-electric-plug-types-will-you-need-an-adapter-in-seoul',
  'xk': 'kosovo-electric-plug-types-will-you-need-an-adapter-in-pristina',
  'kw': 'kuwait-electric-plug-types-will-you-need-an-adapter-in-kuwait-city',
  'kg': 'kyrgyzstan-electric-plug-type-will-you-need-an-adapter',
  'la': 'laos-electric-plug-types-which-adapter-will-you-need-in-laos',
  'lv': 'latvia-electric-plug-type-will-you-need-an-adapter-in-riga',
  'lb': 'lebanon-electric-plug-types-will-you-need-an-adapter-in-beirut',
  'ls': 'lesotho-electric-plug-types-which-adapter-do-you-need-for-lesotho',
  'lr': 'liberia-electric-plug-types-will-you-need-an-adapter-in-liberia',
  'ly': 'libya-electric-plug-types-will-you-need-an-adapter-in-libya',
  'li': 'liechtenstein-electric-plug-types-will-you-need-an-adapter',
  'lt': 'lithuania-electric-plug-types-will-you-need-an-adapter-in-vilnius-2',
  'lu': 'luxembourg-electric-plug-types-will-you-need-an-adapter-in-luxembourg',
  'mg': 'madagascar-electric-plug-types-will-you-need-an-adapter',
  'mw': 'malawi-electric-plug-types-which-adapter-will-you-need-in-malawi',
  'my': 'malaysia-electric-plug-types-will-you-need-an-adapter-in-kuala-lumpur',
  'mv': 'maldives-electric-plug-types-will-you-need-an-adapter-for-maldives',
  'ml': 'mali-electric-plug-types-which-adapter-will-you-need-in-mali',
  'mt': 'malta-electric-plug-types-will-you-need-an-adapter-for-valletta',
  'mh': 'marshall-islands-electric-plug-types-will-you-need-an-adapter',
  'mr': 'mauritania-electric-plug-types-will-you-need-an-adapter',
  'mu': 'mauritius-electric-plug-types-will-you-need-an-adapter',
  'mx': 'mexico-electric-plug-types-will-you-need-an-adapter-in-mexico',
  'fm': 'micronesia-electric-plug-types-will-you-need-an-adapter-on-the-islands',
  'md': 'moldova-electric-plug-types-will-you-need-an-adapter-for-moldova',
  'mc': 'monaco-electric-plug-types-will-you-need-an-adapter-in-monaco',
  'mn': 'mongolia-electric-plug-types-will-you-need-an-adapter-in-the-steppe',
  'me': 'montenegro-electric-plug-types-will-you-need-an-adapter',
  'ma': 'morocco-electric-plug-types-will-you-need-an-adapter-in-morocco',
  'mz': 'mozambique-electric-plug-types-will-you-need-an-adapter',
  'mm': 'myanmar-electric-plug-types-will-you-need-an-adapter-for-myanmar',
  'na': 'namibia-electric-plug-types-which-adapter-will-you-need',
  'nr': 'nauru-electric-plug-types-which-adapter-will-you-need-in-nauru',
  'np': 'nepal-electric-plug-types-will-you-need-an-adapter-in-nepal',
  'nl': 'netherlands-electric-plug-types-will-you-need-an-adapter',
  'nz': 'new-zealand-electric-plug-types-which-adapter-should-you-get',
  'ni': 'nicaragua-electric-plug-types-will-you-need-an-adapter-in-nicaragua',
  'ne': 'niger-electric-plug-types-will-you-need-an-adapter-for-niger',
  'ng': 'nigeria-electric-plug-types-which-adapter-will-you-need',
  'mk': 'north-macedonia-electric-plug-types-will-you-need-an-adapter',
  'no': 'norway-electric-plug-types-will-you-need-an-adapter-for-oslo',
  'om': 'oman-electric-plug-types-which-adapter-will-you-need',
  'pk': 'pakistan-electric-plug-types-will-you-need-an-adapter',
  'pw': 'palau-electric-plug-types-will-you-need-an-adapter-for-palau',
  'pa': 'panama-electric-plug-types-will-you-need-an-adapter-for-panama',
  'pg': 'papua-new-guinea-electric-plug-types-which-adapter-will-you-need',
  'py': 'paraguay-electric-plug-types-which-adapter-will-you-need',
  'pe': 'peru-electric-plug-types-will-you-need-an-adapter-for-peru',
  'ph': 'philippines-electric-plug-types-will-you-need-an-adapter-for-philippines',
  'pl': 'poland-electric-plug-types-will-you-need-an-adapter-in-poland',
  'pt': 'portugal-electric-plug-types-will-you-need-adapter-in-lisbon-porto',
  'qa': 'qatar-electric-plug-types-which-adapter-will-you-need-in-qatar',
  'ro': 'romania-electric-plug-types-will-you-need-an-adapter-in-romania',
  'ru': 'russia-electric-plug-types-will-you-need-an-adapter-in-russia',
  'rw': 'rwanda-electric-plug-types-will-you-need-to-bring-an-adapter-with-you',
  'kn': 'saint-kitts-and-nevis-electric-plug-types-will-you-need-an-adapter',
  'lc': 'saint-lucia-electric-plug-types-which-adapter-will-you-need',
  'vc': 'saint-vincent-and-the-grenadines-electric-plug-types-adapter-a-must',
  'ws': 'samoa-electric-plug-types-will-you-need-an-adapter-for-samoa',
  'sm': 'san-marino-electric-plug-types-will-you-need-an-adapter',
  'st': 'sao-tome-and-principe-electric-plug-types-which-adapter-will-you-need',
  'sa': 'saudi-arabia-electric-plug-types-which-adapter-will-you-need',
  'sn': 'senegal-electric-plug-types-which-adapter-will-you-need-in-dakar',
  'rs': 'serbia-electric-plug-types-which-adapter-will-you-need-in-belgrade',
  'sc': 'seychelles-electric-plug-types-which-adapter-will-you-need-with-you',
  'sl': 'sierra-leone-electric-plug-types-which-adapter-will-you-need-with-you',
  'sg': 'singapore-electric-plug-types-will-you-need-an-adapter-for-singapore',
  'sk': 'slovakia-electric-plug-types-will-you-need-an-adapter-for-bratislava',
  'si': 'slovenia-electric-plug-types-will-you-need-an-adapter-for-slovenia',
  'sb': 'solomon-islands-electric-plug-types-will-you-need-an-adapter-with-you',
  'so': 'somalia-electric-plug-types-which-adapter-will-you-need-in-somalia',
  'za': 'south-africa-electric-plug-types-which-adapter-will-you-need-for-south-africa',
  'es': 'spain-electric-plug-types-will-you-need-an-adapter-for-spain',
  'lk': 'sri-lanka-electric-plug-types-will-you-need-an-adapter-in-sri-lanka',
  'sd': 'sudan-electric-plug-types-which-adapter-will-you-need-in-sudan',
  'sr': 'suriname-electric-plug-types-will-you-need-an-adapter-for-suriname',
  'se': 'sweden-electric-plug-types-will-you-need-an-adapter-for-sweden',
  'ch': 'switzerland-electric-plug-types-will-you-need-an-adapter-with-you',
  'sy': 'syria-electric-plug-types-which-adapter-will-you-need-in-syria',
  'tw': 'taiwan-electric-plug-types-which-adaptor-you-need-for-taiwan',
  'tj': 'tajikistan-electric-plug-types-which-adapter-will-you-need-in-tajikistan',
  'tz': 'tanzania-electric-plug-types-which-adapter-will-you-need-in-tanzania',
  'th': 'thailand-electric-plug-type-will-you-need-an-adapter-for-thailand',
  'tg': 'togo-electric-plug-types-which-adapter-will-you-need-for-togo',
  'to': 'tongo-electric-plug-types-which-adapter-will-you-need-for-tongo',  // Should be tonga
  'tt': 'trinidad-and-tobago-electric-plug-types-will-you-need-an-adapter',
  'tn': 'tunisia-electric-plug-types-which-adapter-will-you-need-for-tunisia',
  'tr': 'turkey-electric-plug-types-will-you-need-an-adapter-for-turkey',
  'tm': 'turkmenistan-electric-plug-types-which-adapter-will-you-need',
  'tv': 'tuvalu-electric-plug-types-which-adapter-will-you-need-for-tuvalu',
  'ug': 'uganda-electric-plug-types-which-adapter-do-you-need-in-uganda',
  'ua': 'ukraine-electric-plug-types-what-kind-of-adapter-do-you-need',
  'ae': 'united-arab-emirates-electric-plug-types-which-adapter-for-uae',
  'gb': 'united-kingdom-electric-plug-types-which-adapter-do-you-need-in-uk',
  'us': 'usa-electric-plug-types-will-you-need-an-adapter-traveling-to-the-us',
  'uy': 'uruguay-electric-plug-types-which-adapter-will-you-need-in-uruguay',
  'uz': 'uzbekistan-electric-plug-types-which-adapter-for-uzbekistan',
  'vu': 'vanuatu-electric-plug-types-which-adapter-do-you-need-for-vanuatu',
  'va': 'vatican-city-electric-plug-types-do-you-need-an-adapter-for-vatican-city',
  've': 'venezuela-electric-plug-types-will-you-need-an-adapter-for-venezuela',
  'vn': 'vietnam-electric-plug-types-which-adapter-will-you-need-for-vietnam',
  'ye': 'yemen-electric-plug-types-do-you-need-an-adapter-for-yemen',
  'zm': 'zambia-electric-plug-types-which-adapter-do-you-need-in-zambia',
  'zw': 'zimbabwe-electric-plug-types-which-adapter-do-you-need-for-zimbabwe',
};

// Update the slugs in our data
Object.keys(countriesData).forEach(iso2 => {
  if (wordpressSlugs[iso2]) {
    countriesData[iso2].slug = wordpressSlugs[iso2];
    console.log(`Updated ${countriesData[iso2].name}: ${wordpressSlugs[iso2]}`);
  } else {
    console.log(`No WordPress slug for ${iso2} (${countriesData[iso2].name})`);
  }
});

// Save the updated data
fs.writeFileSync('./src/data/countries-plugs.json', JSON.stringify(countriesData, null, 2));
console.log('\n✅ Updated country slugs to match WordPress URLs exactly');
console.log('Total countries updated:', Object.keys(wordpressSlugs).length);